CREATE TABLE IF NOT EXISTS epps_questions (
    id BIGSERIAL PRIMARY KEY,
    item_no INTEGER NOT NULL UNIQUE CHECK (item_no BETWEEN 1 AND 225),
    statement_a TEXT NOT NULL,
    statement_b TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO epps_questions (item_no, statement_a, statement_b) VALUES
    (1, 'Saya suka menolong teman-teman saya, bila mereka berada dalam kesulitan.', 'Saya ingin melakukan pekerjaan apa saja sebaik mungkin.'),
    (2, 'Saya ingin mengetahui bagaimana pandangan orang-orang besar mengenai berbagai masalah yang menarik perhatian saya.', 'Saya ingin menjadi seorang ahli yang diakui dalam salah satu pekerjaan, jabatan atau bidang khusus.'),
    (3, 'Saya ingin agar setiap pekerjaan tulisan saya teliti, rapi dan tersusun dengan baik.', 'Saya ingin menjadi seorang ahli yang diakui dalam salah satu pekerjaan, jabatan atau bidang khusus.'),
    (4, 'Saya suka menceritakan cerita-cerita yang lucu dan lelucon-lelucon waktu pesta.', 'Saya ingin menulis roman atau sandiwara yang hebat.'),
    (5, 'Saya ingin dapat berbuat sekehendak hati saya.', 'Saya ingin bisa mengatakan bahwa saya telah melakukan dengan baik suatu pekerjaan yang sulit.'),
    (6, 'Saya ingin dapat memecahkan teka-teki dan persoalan-persoalan yang sukar bagi orang lain.', 'Saya suka mengikuti petunjuk-petunjuk dan melakukan apa yang diharapkan orang dari diri saya.'),
    (7, 'Saya ingin mengalami hal-hal yang baru dan perubahan-perubahan dalam kehidupan saya sehari-hari.', 'Saya suka menyatakan pada atasan-atasan saya, bahwa mereka telah melakukan sesuatu pekerjaan dengan baik, bila memang demikian menurut pikiran saya.'),
    (8, 'Saya suka merencanakan dan mengatur detail-detail dari setiap pekerjaan yang harus saya lakukan.', 'Saya suka mengikuti petunjuk-petunjuk dan melakukan apa yang diharapkan orang dari diri saya.'),
    (9, 'Saya ingin orang-orang memperhatikan dan memberikan komentar mengenai penampilan saya di depan umum.', 'Saya suka membaca riwayat hidup orang-orang besar.'),
    (10, 'Saya suka mengelakkan keadaan-keadaan dimana saya diharapkan akan berlaku secara konvensional (kebiasaan umum).', 'Saya suka membaca riwayat hidup orang-orang besar.'),
    (11, 'Saya ingin menjadi seorang ahli yang diakui dalam salah satu pekerjaan, jabatan atau bidang khusus.', 'Saya ingin agar pekerjaan saya diatur dan direncanakan sebelum dimulai.'),
    (12, 'Saya ingin mengetahui bagaimana pandangan orang-orang besar / ahli mengenai berbagai masalah yang menarik perhatian saya.', 'Seandainya saya harus bepergian, maka saya ingin segala sesuatunya telah direncanakan terlebih dahulu.'),
    (13, 'Saya ingin mengerjakan sampai selesai setiap pekerjaan ataupun tugas yang telah saya mulai.', 'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.'),
    (14, 'Saya suka bercerita kepada orang-orang lain tentang petualangan-petualangan saya dan hal-hal aneh yang pernah saya alami.', 'Saya suka makan saya teratur dan ada waktu-waktu tertentu untuk makan.'),
    (15, 'Saya ingin tidak tergantung dari orang lain dalam menentukan apa yang akan saya lakukan.', 'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.'),
    (16, 'Saya ingin bisa mengerjakan segala sesuatu lebih baik daripada orang-orang lain.', 'Saya suka menceritakan cerita-cerita lucu dan lelucon-lelucon waktu pesta.'),
    (17, 'Saya suka mengikuti adat-istiadat dan menghindarkan melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati.', 'Saya suka berbicara tentang hal-hal yang telah saya capai.'),
    (18, 'Saya ingin agar hidup saya teratur sedemikian rupa sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya.', 'Saya suka bercerita kepada orang-orang lain tentang petualangan-petualangan saya dan hal-hal aneh yang pernah saya alami.'),
    (19, 'Saya suka membaca buku-buku atau sandiwara-sandiwara yang terutama berkisar sekitar soal-soal sex.', 'Saya suka menjadi pusat perhatian dalam suatu kelompok.'),
    (20, 'Saya suka mengecam orang-orang yang mempunyai kedudukan sebagai yang berwenang.', 'Saya suka menggunakan kata-kata yang maknanya seringkali tidak diketahui oleh orang lain.'),
    (21, 'Saya ingin menyelesaikan tugas-tugas yang dianggap orang membutuhkan ketrampilan serta usaha.', 'Saya ingin dapat berbuat sekehendak hati saya.'),
    (22, 'Saya suka memuji seseorang yang saya kagumi.', 'Saya ingin merasa bebas untuk melakukan apa yang saya kehendaki.'),
    (23, 'Saya suka menyimpan surat-surat, bon-bon dan kertas-kertas lain secara tersusun rapi dan menurut sistem tertentu.', 'Saya ingin tidak tergantung dari orang lain dalam menentukan apa yang akan saya lakukan.'),
    (24, 'Saya suka mengajukan pertanyaan-pertanyaan yang setahu saya tak seorang pun akan bisa menjawabnya.', 'Saya suka mengecam orang-orang yang mempunyai kedudukan sebagai yang berwenang.'),
    (25, 'Saya menjadi sedemikian marahnya sehingga rasanya ingin melemparkan dan merusak barang-barang.', 'Saya suka mengelakan tanggung jawab dan kewajiban-kewajiban.'),
    (26, 'Saya ingin berhasil dalam apa yang saya lakukan.', 'Saya suka membuat teman-teman baru.'),
    (27, 'Saya suka mengikuti petunjuk-petunjuk dan melakukan apa yang diharapkan orang lain dari diri saya.', 'Saya ingin mempunyai ikatan perasaan yang kuat dengan teman-teman saya.'),
    (28, 'Saya ingin agar setiap pekerjaan tulisan saya teliti, rapi dan tersusun dengan baik.', 'Saya ingin membuat teman sebanyak mungkin.'),
    (29, 'Saya suka menceritakan cerita-cerita lucu dan lelucon-lelucon waktu pesta.', 'Saya suka berkirim surat pada teman-teman saya.'),
    (30, 'Saya ingin dapat berbuat sekehendak hati saya.', 'Saya suka bersama-sama dengan teman-teman saya melakukan atau menjalani sesuatu.'),
    (31, 'Saya ingin dapat memecahkan teka-teki dan persoalan-persoalan yang sukar bagi orang lain.', 'Saya suka menilai orang-orang berdasarkan sebab-sebab mereka melakukan sesuatu dan bukan atas dasar yang sesungguhnya mereka lakukan.'),
    (32, 'Saya suka menerima pimpinan orang-orang yang saya kagumi.', 'Saya ingin memahami bagaimana perasaan teman-teman saya dalam menghadapi berbagai masalah.'),
    (33, 'Saya suka makan saya teratur dan ada waktu-waktu tertentu untuk makan.', 'Saya suka mempelajari dan menganalisa tingkah laku orang-orang lain.'),
    (34, 'Saya ingin mengatakan hal-hal yang dianggap lucu dan cerdas oleh orang-orang lain.', 'Saya suka menempatkan diri saya dalam kedudukan orang lain, dan membayangkan bagaimana perasaan saya bila berada dalam keadaan yang sama.'),
    (35, 'Saya ingin merasa bebas untuk melakukan apa yang saya kehendaki.', 'Saya suka mengamati-amati bagaimana perasaan orang lain dalam keadaan tertentu.'),
    (36, 'Saya ingin menyelesaikan tugas-tugas yang dianggap orang membutuhkan keterampilan serta usaha.', 'Saya ingin teman-teman memberikan dorongan-dorongan kepada saya bila saya menghadapi kegagalan.'),
    (37, 'Dalam merencanakan sesuatu, saya ingin mendapat saran-saran dari orang-orang yang pendapatnya saya hormati.', 'Saya ingin diperlakukan dengan ramah oleh teman-teman saya.'),
    (38, 'Saya ingin agar hidup saya teratur sedemikian rupa sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana saya.', 'Saya ingin teman-teman saya merasa kasihan pada saya apabila saya sakit.'),
    (39, 'Saya suka menjadi pusat perhatian dalam suatu kelompok.', 'Saya ingin agar teman-teman saya meributkan tentang diri saya apabila saya mendapatkan cedera atau sakit.'),
    (40, 'Saya suka mengelakan keadaan-keadaan dimana saya diharapkan akan berlaku secara konvensional (kebiasaan umum).', 'Saya ingin agar teman-teman saya bersimpati terhadap saya dan menghibur saya bila saya bersusah hati.'),
    (41, 'Saya ingin menulis roman atau sandiwara yang hebat.', 'Bila saya termasuk dalam suatu kepanitian, saya ingin ditunjuk atau dipilih sebagai ketuanya.'),
    (42, 'Bila saya berada dalam suatu kelompok, saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok itu.', 'Saya ingin mengawasi dan mengarahkan tindakan-tindakan orang lain bilamana saja mungkin.'),
    (43, 'Saya suka menyimpan surat-surat, bon-bon dan kertas-kertas lainnya secara tersusun rapi dan menurut sistem tertentu.', 'Saya ingin menjadi salah seorang pemimpin dalam organisasi-organisasi atau kelompok-kelompok dimana saya menjadi anggotanya.'),
    (44, 'Saya suka mengajukan pertanyaan-pertanyaan yang setahu saya tak seorang pun akan bisa menjawabnya.', 'Saya suka mengatakan pada orang-orang lain bagaimana mereka harus melakukan pekerjaan mereka.'),
    (45, 'Saya suka mengelakan tanggung jawab dan kewajiban-kewajiban.', 'Saya ingin diminta untuk menyelesaikan perdebatan-perdebatan atau perselisihan-perselisihan antara orang-orang lain.'),
    (46, 'Saya ingin menjadi seorang ahli yang diakui dalam suatu pekerjaan, jabatan atau bidang yang khusus.', 'Saya merasa bersalah apabila saya telah melakukan sesuatu yang saya ketahui adalah tidak baik.'),
    (47, 'Saya suka membaca riwayat hidup orang-orang besar.', 'Saya merasa bahwa saya harus mengakui hal-hal yang telah saya lakukan dan saya anggap tidak baik.'),
    (48, 'Saya suka merencanakan dan mengatur detail-detail setiap pekerjaan yang harus saya lakukan.', 'Bila keadaan kurang menguntungkan bagi saya, maka saya merasa bahwa saya harus lebih disalahkan daripada orang lain.'),
    (49, 'Saya suka menggunakan kata-kata yang maknanya sering tidak diketahui oleh orang lain.', 'Saya merasa dalam banyak hal, saya kalah bila dibandingkan dengan orang-orang lain.'),
    (50, 'Saya suka mengecam orang-orang yang mempunyai kedudukan sebagai yang berwenang.', 'Saya merasa canggung di tengah-tengah orang-orang lain yang saya anggap sebagai atasan saya.'),
    (51, 'Saya ingin melakukan pekerjaan apa saja sebaik mungkin.', 'Saya suka menolong orang-orang yang tidak begitu beruntung seperti saya.'),
    (52, 'Saya ingin mengetahui bagaimana pandangan orang-orang besar mengenai berbagai masalah yang menarik perhatian saya.', 'Saya suka bermurah hati terhadap teman-teman saya.'),
    (53, 'Saya suka membuat rencana sebelum memulai pekerjaan yang sulit.', 'Saya suka memberi pertolongan-pertolongan kecil kepada teman-teman saya.'),
    (54, 'Saya suka bercerita kepada orang-orang lain tentang petualangan-petualangan saya dan hal-hal aneh yang pernah saya alami.', 'Saya ingin teman-teman saya mempercayai saya dan menceritakan kesulitan-kesulitan mereka kepada saya.'),
    (55, 'Saya suka menyatakan pendapat saya tentang berbagai hal.', 'Saya suka memaafkan teman-teman saya yang kadang-kadang mungkin menyakiti hati saya.'),
    (56, 'Saya ingin mengerjakan segala sesuatu lebih baik daripada orang-orang lain.', 'Saya suka makan di restoran-restoran yang baru atau asing.'),
    (57, 'Saya suka mengikuti adat istiadat dan menghindarkan untuk melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati.', 'Saya suka mengikuti mode-mode baru.'),
    (58, 'Saya ingin pekerjaan saya diatur dan direncanakan sebelum dimulai.', 'Saya suka bepergian melihat-lihat daerah pedalaman.'),
    (59, 'Saya ingin orang-orang memperhatikan dan memberikan komentar mengenai penampilan saya di depan umum.', 'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat.'),
    (60, 'Saya ingin tidak tergantung dari orang lain dalam menentukan apa yang akan saya lakukan.', 'Saya suka mengerjakan hal-hal yang baru dan lain.'),
    (61, 'Saya ingin bisa mengatakan bahwa saya telah melakukan dengan baik sesuatu pekerjaan yang sulit.', 'Saya suka bekerja keras pada tiap pekerjaan yang saya hadapi.'),
    (62, 'Saya suka mengatakan pada atasan-atasan saya bahwa mereka telah melakukan sesuatu pekerjaan dengan baik, bila memang demikian halnya, menurut pikiran saya.', 'Saya ingin menyelesaikan pekerjaan satu per satu sebelum memulai yang lainnya.'),
    (63, 'Seandainya saya harus bepergian, maka saya ingin agar segala sesuatunya telah direncanakan terlebih dahulu.', 'Saya suka mengerjakan teka-teki atau memecahkan persoalan-persoalan sampai selesai.'),
    (64, 'Saya kadang-kadang suka melakukan hal-hal hanya untuk melihat bagaimana efeknya terhadap orang lain.', 'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tidak akan berhasil.'),
    (65, 'Saya suka melakukan hal-hal yang dianggap orang lain tidak sesuai dengan adat kebiasaan.', 'Saya ingin bekerja berjam-jam tanpa diganggu.'),
    (66, 'Saya ingin mengerjakan sesuatu yang berarti.', 'Saya suka mencium orang yang menarik dari lawan jenis saya.'),
    (67, 'Saya suka memuji seseorang yang saya kagumi.', 'Saya ingin dianggap punya daya tarik fisik oleh orang-orang dari lawan jenis saya.'),
    (68, 'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.', 'Saya suka jatuh cinta pada seseorang dari lawan jenis saya.'),
    (69, 'Saya suka berbicara tentang hal-hal yang telah saya capai.', 'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal sex.'),
    (70, 'Saya ingin melakukan hal-hal dengan cara saya sendiri tanpa menghiraukan apa yang mungkin dipikirkan orang lain.', 'Saya suka membaca buku-buku dan sandiwara yang terutama berkisar sekitar soal sex.'),
    (71, 'Saya ingin menulis roman atau sandiwara yang hebat.', 'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya.'),
    (72, 'Bila saya berada dalam suatu kelompok, saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok.', 'Saya rasanya ingin mengecam seseorang di muka umum bila orang itu memang patut menerimanya.'),
    (73, 'Saya ingin agar hidup saya teratur sedemikian rupa sehingga berjalan lancar dan tanpa banyak perubahan dalam rencana-rencana saya.', 'Saya menjadi sedemikian marahnya sehingga rasanya ingin melemparkan dan merusak barang-barang.'),
    (74, 'Saya suka mengajukan pertanyaan-pertanyaan yang setahu saya, tak seorangpun akan bisa menjawabnya.', 'Saya suka mengatakan kepada orang-orang lain bagaimana pendapat saya mengenai mereka.'),
    (75, 'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban.', 'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh.'),
    (76, 'Saya ingin loyal terhadap teman-teman saya.', 'Saya ingin melakukan pekerjaan apa saja sebaik mungkin.'),
    (77, 'Saya suka mengamat-amati bagaimana perasaan orang lain dalam suatu keadaan tertentu.', 'Saya ingin bisa mengatakan bahwa saya telah melakukan dengan baik sesuatu pekerjaan yang sulit.'),
    (78, 'Saya ingin teman-teman saya memberi dorongan kepada saya bila saya menghadapi kegagalan.', 'Saya ingin bisa mengerjakan segala sesuatu lebih baik daripada orang-orang lain.'),
    (79, 'Saya ingin menjadi salah seorang pemimpin dalam organisasi-organisasi atau kelompok-kelompok di mana saya menjadi anggota.', 'Saya ingin bisa mengerjakan segala sesuatu lebih baik daripada orang-orang lain.'),
    (80, 'Bila keadaan kurang menguntungkan bagi saya, maka saya merasa bahwa saya harus lebih disalahkan daripada orang lain.', 'Saya ingin dapat memecahkan teka-teki dan persoalan-persoalan yang sukar bagi orang lain.'),
    (81, 'Saya suka melakukan sesuatu untuk teman-teman saya.', 'Dalam merencanakan sesuatu saya ingin mendapat saran-saran dari orang-orang yang pendapatnya saya hormati.'),
    (82, 'Saya suka menempatkan diri saya ke dalam kedudukan orang lain dan membayangkan bagaimana perasaan saya bila berada dalam keadaan yang sama.', 'Saya suka mengatakan kepada atasan-atasan saya bahwa mereka telah melakukan sesuatu pekerjaan dengan baik, bila menurut pikiran saya memang demikian halnya.'),
    (83, 'Saya ingin agar teman-teman saya menunjukkan simpati dan pengertian bila saya mengalami kesukaran-kesukaran.', 'Saya ingin menyelesaikan tugas-tugas yang dianggap orang membutuhkan keterampilan serta usaha.'),
    (84, 'Bila saya termasuk dalam suatu kepanitiaan, saya ingin ditunjukan atau dipilih sebagai ketuanya.', 'Bila saya berada dalam suatu kelompok, saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok itu.'),
    (85, 'Apabila saya melakukan sesuatu hal yang salah, saya merasa bahwa untuk itu saya harus dihukum.', 'Saya suka mengikuti adat istiadat dan menghindarkan untuk melakukan hal-hal yang mungkin dianggap tidak wajaroleh orang-orang yang saya hormati.'),
    (86, 'Saya suka bersama-sama dengan teman-teman saya melakukan atau menjalani sesuatu.', 'Saya suka membuat perencanaan sebelum memulai pekerjaan yang sulit.'),
    (87, 'Saya ingin memahami bagaimana perasaan teman-teman saya dalam menghadapi berbagai masalah.', 'Seandainya saya harus bepergian, maka saya ingin agar segala sesuatunya telah direncanakan terlebih dahulu.'),
    (88, 'Saya ingin diperlakukan dengan ramah oleh teman-teman saya.', 'Saya ingin pekerjaan saya diatur dan direncanakan sebelum dimulai.'),
    (89, 'Saya ingin dianggap sebagai pemimpin oleh orang-orang lain.', 'Saya suka menyimpan surat-surat, bon-bon dan kertas-kertas lain secara tersusun rapi dan menurut sistem tertentu.'),
    (90, 'Saya merasa bahwa pilu hati dan kesusahan yang telah saya alami lebih banyak membawa kebaikan daripada kerugian bagi saya.', 'Saya ingin agar hidup saya teratur sedemikian rupa sehingga berjalan lancar dan tanpa banyak perubahan dalam rencana-rencana saya.'),
    (91, 'Saya ingin mempunyai ikatan perasaan yang kuat dengan teman-teman saya.', 'Saya ingin mengatakan hal-hal yang dianggap lucu dan cerdas oleh orang-orang lain.'),
    (92, 'Saya suka merenungkan kepribadian teman-teman saya dan mencoba mengerti sebab-sebab yang menjadikan mereka sebagaimana terlihat.', 'Saya kadang-kadang suka melakukan hal-hal hanya untuk melihat bagaimana efeknya terhadap orang-orang.'),
    (93, 'Saya ingin agar teman-teman saya meributkan tentang diri saya bila saya mendapat cedera atau sakit.', 'Saya suka berbicara tentang hal-hal yang telah saya capai.'),
    (94, 'Saya suka mengatakan kepada orang-orang bagaimana mereka harus melakukan pekerjaan mereka.', 'Saya suka menjadi pusat perhatian dalam suatu kelompok.'),
    (95, 'Saya merasa canggung di tengah orang-orang yang saya anggap sebagai atasan saya.', 'Saya suka menggunakan kata-kata yang maknanya sering tidak diketahui oleh orang lain.'),
    (96, 'Saya lebih suka mengerjakan sesuatu bersama-sama dengan teman-teman saya daripada sendirian.', 'Saya suka menyatakan pendapat saya tentang berbagai hal.'),
    (97, 'Saya suka mempelajari dan menganalisa tingkah laku orang-orang lain.', 'Saya suka melakukan hal-hal yang dianggap orang lain tidak sesuai dengan adat kebiasaan.'),
    (98, 'Saya ingin agar teman-teman saya merasa kasihan pada saya bila saya sakit.', 'Saya suka mengelakkan keadaan dimana saya diharapkan akan berlaku secara konvensional (kebiasaan umum).'),
    (99, 'Saya ingin mengawasi dan mengarahkan tindakan-tindakan orang lain bilamana saja mungkin.', 'Saya suka melakukan hal-hal dengan cara saya sendiri tanpa menghiraukan apa yang mungkin dipikirkan orang lain.'),
    (100, 'Saya merasa bahwa dalam banyak hal saya kalah bila dibandingkan dengan orang lain.', 'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban.'),
    (101, 'Saya ingin berhasil dalam apa yang saya lakukan.', 'Saya suka membuat teman-teman baru.'),
    (102, 'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu.', 'Saya ingin membuat teman saya sebanyak mungkin.'),
    (103, 'Saya ingin agar teman-teman saya membantu apabila saya mengalami kesulitan.', 'Saya suka melakukan sesuatu untuk teman-teman saya.'),
    (104, 'Saya suka memperdebatkan pendirian saya bila diserang oleh orang-orang lain.', 'Saya suka berkirim surat kepada teman-teman saya.'),
    (105, 'Saya merasa bersalah apabila saya telah melakukan sesuatu hal yang saya ketahui adalah tidak baik.', 'Saya ingin mempunyai ikatan perasaan yang kuat dengan teman-teman saya.'),
    (106, 'Saya suka bersama-sama dengan teman-teman saya melakukan atau menjalani sesuatu.', 'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu.'),
    (107, 'Saya suka menerima pimpinan orang-orang yang saya kagumi.', 'Saya ingin memahami perasaan teman-teman saya dalam menghadapi berbagai masalah.'),
    (108, 'Saya ingin agar teman-teman saya dengan gembira memberikan pertolongan-pertolongan kecil kepada saya.', 'Saya suka menilai orang-orang berdasarkan sebab-sebab mereka melakukan sesuatu dan bukannya atas dasar apa yang sesungguhnya mereka lakukan.'),
    (109, 'Bila saya berada dalam suatu kelompok, saya ingin menentukan apa yang akan kami kerjakan.', 'Saya suka meramalkan bagaimana teman-teman saya akan bertindak dalam berbagai situasi.'),
    (110, 'Saya lebih suka bila saya mengalah dan menghindarkan perkelahian daripada bila saya mencoba memaksakan kemauan saya.', 'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu.'),
    (111, 'Saya suka membuat teman-teman baru.', 'Saya ingin agar teman-teman saya membantu saya bila saya mengalami kesulitan.'),
    (112, 'Saya suka menilai orang-orang berdasarkan sebab-sebab mereka melakukan sesuatu dan bukan atas dasar apa yang sesungguhnya mereka lakukan.', 'Saya ingin teman-teman saya banyak menunjukkan rasa sayang mereka terhadap saya.'),
    (113, 'Saya ingin agar hidup saya teratur sedemikian rupa sehingga berjalan lancar dan tanpa banyak perubahan-perubahan dalam rencana-rencana saya.', 'Saya ingin agar teman-teman saya merasa kasihan pada saya apabila saya sakit.'),
    (114, 'Saya ingin diminta untuk menyelesaikan perdebatan-perdebatan atau perselisihan-perselisihan antara orang-orang lain.', 'Saya ingin agar teman-teman saya dengan gembira memberikan pertolongan-pertolongan kecil pada saya.'),
    (115, 'Saya merasa saya harus mengakui hal-hal yang telah saya lakukan dan saya anggap tidak baik.', 'Saya ingin teman-teman saya bersimpati terhadap saya dan menghibur saya bila saya bersusah hati.'),
    (116, 'Saya lebih suka melakukan sesuatu dengan teman saya daripada sendirian.', 'Saya suka memperdebatkan pendirian saya bila diserang orang lain.'),
    (117, 'Saya suka merenungkan kepribadian teman-teman saya dan mencoba mengerti sebab-sebab yang menjadikan mereka sebagaimana terlihat.', 'Saya ingin mampu membujuk dan mempengaruhi orang lain untuk melakukan apa yang saya kehendaki.'),
    (118, 'Saya ingin teman-teman saya bersimpati terhadap saya dan menghibur saya bila saya bersusah hati.', 'Bila saya berada dalam suatu kelompok, saya ingin menentukan apa yang akan kami lakukan.'),
    (119, 'Saya suka mengajukan pertanyaan yang setahu saya tak seorang pun akan bisa menjawabnya.', 'Saya suka menyatakan kepada orang lain bagaimana mereka harus melakukan pekerjaan mereka.'),
    (120, 'Saya merasa canggung di tengah orang-orang yang saya anggap sebagai atasan saya.', 'Saya ingin mengawasi dan mengarahkan tindakan-tindakan orang lain bilamana saja mungkin.'),
    (121, 'Saya suka bergaul dalam lingkungan di mana para anggotanya mempunyai perasaan-perasaan yang akrab satu sama lainnya.', 'Saya merasa bersalah apabila saya telah melakukan sesuatu hal yang saya ketahui adalah tidak baik.'),
    (122, 'Saya suka menganalisa perasaan orang lain dan sebab-sebab mereka melakukan sesuatu.', 'Saya merasa sedih oleh ketidakmampuan saya sendiri untuk menghadapi perbagai macam keadaan.'),
    (123, 'Saya ingin agar teman-teman saya merasa kasihan pada saya bila saya sakit.', 'Saya lebih suka bila saya mengalah dan menghindarkan perkelahian daripada bila saya mencoba memaksakan kemauan saya.'),
    (124, 'Saya ingin mampu membujuk dan mempengaruhi orang lain untuk melakukan apa yang saya kehendaki.', 'Saya merasa sedih oleh ketidakmampuan saya sendiri untuk menghadapi berbagai macam keadaan.'),
    (125, 'Saya suka mengecam orang-orang yang mempunyai kedudukan sebagai yang berwenang.', 'Saya merasa canggung di tengah orang-orang yang saya anggap sebagai atasan saya.'),
    (126, 'Saya suka bergaul dalam lingkungan dimana para anggotanya mempunyai perasaan yang akrab satu sama lainnya.', 'Saya suka menolong teman-teman saya bila mereka berada dalam kesulitan.'),
    (127, 'Saya suka menganalisa perasaan-perasaan saya dan sebab-sebab mengapa saya melakukan sesuatu.', 'Saya suka menunjukkan simpati saya kepada teman-teman saya bila mereka mendapat cedera atau sakit.'),
    (128, 'Saya ingin agar teman-teman saya membantu saya bila saya mengalami kesulitan.', 'Saya suka memperlakukan orang lain dengan ramah dan simpatik.'),
    (129, 'Saya ingin menjadi salah seorang pemimpin dalam organisasi atau kelompok-kelompok yang saya masuki.', 'Saya suka menunjukkan simpati saya kepada teman-teman saya bila mereka mendapat cedera atau sakit.'),
    (130, 'Saya merasa bahwa pilu hati dan penderitaan yang telah saya alami lebih banyak membawa kebaikan daripada kerugian bagi diri saya.', 'Saya suka berlaku sangat ramah terhadap teman-teman saya.'),
    (131, 'Saya lebih suka melakukan sesuatu bersama-sama teman saya daripada sendirian.', 'Saya suka bereksperimen dan melakukan hal-hal yang baru.'),
    (132, 'Saya suka merenungkan kepribadian teman-teman saya dan mencoba memahami apa yang menjadikan mereka sebagaimana terlihat.', 'Saya lebih suka mencoba pekerjaan-pekerjaan yang baru dan lain daripada terus-menerus melakukan pekerjaan yang sama.'),
    (133, 'Saya ingin agar teman-teman saya menunjukkan simpati dan pengertian bila saya mengalami kesukaran-kesukaran.', 'Saya suka bertemu dengan orang-orang baru.'),
    (134, 'Saya suka memperdebatkan pendirian saya bila diserang orang lain.', 'Saya ingin mengalami hal-hal yang baru dan perubahan-perubahan dalam kehidupan saya sehari-hari.'),
    (135, 'Saya lebih suka bila saya mengalah dan menghindarkan perkelahian daripada bila saya mencoba memaksakan kemauan saya.', 'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat.'),
    (136, 'Saya suka melakukan sesuatu untuk teman-teman saya.', 'Bila saya harus melakukan suatu tugas, saya ingin mengerjakannya sampai selesai.'),
    (137, 'Saya suka menganalisa perasaan orang lain dan sebab-sebab mengapa mereka melakukan sesuatu.', 'Saya ingin menghindarkan gangguan bila saya sedang bekerja.'),
    (138, 'Saya ingin agar teman-teman saya dengan gembira memberikan pertolongan-pertolongan kecil kepada saya.', 'Saya suka bekerja sampai jauh malam untuk menyelesaikan suatu pekerjaan.'),
    (139, 'Saya ingin dianggap sebagai seorang pemimpin oleh orang-orang lain.', 'Saya ingin bekerja berjam-jam tanpa diganggu.'),
    (140, 'Bila saya melakukan sesuatu yang salah, saya merasa bahwa untuk itu saya harus dihukum.', 'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tak akan berhasil.'),
    (141, 'Saya ingin loyal terhadap teman-teman saya.', 'Saya suka bepergian dengan (untuk laki-laki) wanita-wanita yang menarik (untuk wanita) laki-laki yang menarik.'),
    (142, 'Saya suka meramalkan bagaimana teman-teman saya akan bertindak dalam berbagai situasi.', 'Saya suka ikut serta dalam diskusi-diskusi tentang sex dan aktivitas sexuil.'),
    (143, 'Saya ingin teman-teman saya banyak menunjukkan rasa sayang mereka terhadap saya.', 'Saya suka nafsu saya terangsang.'),
    (144, 'Bila saya berada dalam suatu kelompok, saya ingin menentukan apa yang akan kami kerjakan.', 'Saya suka bersibuk diri dengan aktivitas-aktivitas sosial bersama-sama dengan orang-orang dari lawan jenis saya.'),
    (145, 'Saya merasa sedih oleh ketidakmampuan saya sendiri untuk menghadapi berbagai macam keadaan.', 'Saya suka membaca buku-buku dan sandiwara-sandiwara yang terutama berkisar sekitar soal-soal sex.'),
    (146, 'Saya suka berkirim surat kepada teman-teman saya.', 'Saya suka membaca berita-berita surat kabar tentang pembunuhan-pembunuhan dan lain-lain perbuatan kekerasan.'),
    (147, 'Saya suka meramalkan bagaimana teman-teman saya akan bertindak dalam berbagai situasi.', 'Saya suka menyerang pendirian yang bertentangan dengan pendirian saya.'),
    (148, 'Saya ingin teman-teman saya meributkan tentang diri saya, bila saya mendapat cedera atau sakit.', 'Saya rasanya ingin menyalahkan orang lain bila keadaannya kurang menguntungkan bagi saya.'),
    (149, 'Saya suka menyatakan kepada orang-orang lain bagaimana mereka harus melakukan pekerjaan mereka.', 'Saya rasanya ingin membalas dendam bila seseorang menghina saya.'),
    (150, 'Saya merasa bahwa dalam banyak hal saya kalah bila dibandingkan dengan orang lain.', 'Saya rasanya ingin menghardik orang lain bila saya berbeda pendapat dengan mereka.'),
    (151, 'Saya suka menolong teman-teman saya bila mereka berada dalam kesulitan.', 'Saya ingin melakukan pekerjaan apa saja sebaik mungkin.'),
    (152, 'Saya suka bepergian melihat-lihat daerah pedalaman.', 'Saya ingin menyelesaikan tugas-tugas yang dianggap orang membutuhkan keterampilan serta usaha.'),
    (153, 'Saya suka bekerja keras pada tiap pekerjaan yang saya hadapi.', 'Saya ingin mengerjakan sesuatu yang berarti.'),
    (154, 'Saya suka bepergian dengan (untuk laki-laki) wanita-wanita yang menarik (untuk wanita) laki-laki yang menarik.', 'Saya ingin berhasil dalam apa yang saya lakukan.'),
    (155, 'Saya suka membaca berita-berita surat kabar tentang pembunuhan-pembunuhan dan lain-lain perbuatan kekerasan.', 'Saya ingin menulis roman atau sandiwara yang hebat.'),
    (156, 'Saya suka memberikan pertolongan-pertolongan kecil kepada teman-teman saya.', 'Dalam merencanakan sesuatu, saya ingin mendapat saran-saran dari orang-orang yang pendapatnya saya hormati.'),
    (157, 'Saya ingin mengalami hal-hal yang baru dan perubahan-perubahan dalam kehidupan saya sehari-hari.', 'Saya suka menyatakan pada atasan saya bahwa mereka telah melakukan suatu pekerjaan dengan baik, bila memang demikian halnya menurut pikiran saya.'),
    (158, 'Saya suka bekerja sampai jauh malam untuk menyelesaikan suatu pekerjaan.', 'Saya suka memuji seseorang yang saya kagumi.'),
    (159, 'Saya suka nafsu saya terangsang.', 'Saya suka menerima pimpinan dari orang-orang yang saya kagumi.'),
    (160, 'Saya rasanya ingin membalas dendam bila seseorang menghina saya.', 'Bila saya berada dalam suatu kelompok, saya suka menerima pimpinan orang lain dalam memutuskan apa yang akan dilakukan oleh kelompok itu.'),
    (161, 'Saya suka bermurah hati terhadap teman-teman saya.', 'Saya suka membuat rencana sebelum memulai pekerjaan yang sulit.'),
    (162, 'Saya suka bertemu dengan orang-orang baru.', 'Saya ingin agar setiap pekerjaan tulisan saya teliti, rapi dan tersusun dengan baik.'),
    (163, 'Saya ingin mengerjakan sampai selesai setiap pekerjaan ataupun tugas yang telah saya mulai.', 'Saya ingin barang-barang saya tersusun rapi dan teratur di atas meja atau di dalam ruang kerja saya.'),
    (164, 'Saya ingin dianggap mempunyai daya tarik fisik oleh orang-orang dari lawan jenis saya.', 'Saya suka merencanakan dan mengatur detail-detail dari setiap pekerjaan yang harus saya lakukan.'),
    (165, 'Saya suka mengatakan kepada orang-orang lain bagaimana pendapat saya mengenai mereka.', 'Saya suka makan saya teratur dan ada waktu tertentu untuk makan.'),
    (166, 'Saya suka berlaku sangat ramah terhadap teman-teman saya.', 'Saya ingin mengatakan hal-hal yang dianggap lucu dan cerdas oleh orang-orang lain.'),
    (167, 'Saya lebih suka mencoba pekerjaan yang baru dan lain daripada terus-menerus melakukan pekerjaan yang sama.', 'Saya kadang-kadang suka melakukan hal-hal hanya untuk melihat bagaimana efeknya terhadap orang lain.'),
    (168, 'Saya suka bertahan menghadapi satu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tidak akan berhasil.', 'Saya ingin orang-orang memperhatikan dan memberikan komentar mengenai penampilan saya di depan umum.'),
    (169, 'Saya suka membaca buku-buku dan sandiwara-sandiwara yang terutama berkisar sekitar soal-soal sex.', 'Saya suka menjadi pusat perhatian dalam suatu kelompok.'),
    (170, 'Saya rasanya ingin menyalahkan orang-orang lain bila keadaan kurang menguntungkan bagi saya.', 'Saya suka mengajukan pertanyaan-pertanyaan yang setahu saya tak seorang pun akan bisa menjawabnya.'),
    (171, 'Saya suka menunjukkan simpati saya kepada teman-teman saya bila mereka mendapat cedera atau sakit.', 'Saya suka mengatakan pendapat saya tentang berbagai hal.'),
    (172, 'Saya suka makan di restoran-restoran yang baru atau asing.', 'Saya suka melakukan hal-hal yang dianggap orang lain tidak sesuai dengan adat kebiasaan.'),
    (173, 'Saya ingin menyelesaikan pekerjaan satu per satu sebelum memulai yang baru.', 'Saya ingin merasa bebas untuk melakukan apa yang saya kehendaki.'),
    (174, 'Saya suka ikut serta dalam diskusi-diskusi tentang sex dan aktivitas sexuil.', 'Saya ingin melakukan hal-hal dengan cara saya sendiri tanpa menghiraukan apa yang mungkin dipikirkan orang lain.'),
    (175, 'Saya menjadi sedemikian marahnya sehingga rasanya ingin melemparkan dan merusak barang-barang.', 'Saya suka mengelakan tanggung jawab dan kewajiban-kewajiban.'),
    (176, 'Saya suka menolong teman-teman saya bila mereka berada dalam kesulitan.', 'Saya ingin loyal terhadap teman-teman saya.'),
    (177, 'Saya suka melakukan hal-hal yang baru.', 'Saya suka membuat teman-teman baru.'),
    (178, 'Bila saya harus melakukan suatu tugas, saya ingin mengerjakannya sampai selesai.', 'Saya suka bergaul dalam lingkungan dimana para anggotanya mempunyai perasaan yang akrab satu sama lainnya.'),
    (179, 'Saya suka bepergian dengan (untuk laki-laki) wanita-wanita yang menarik (untuk wanita) laki-laki yang menarik.', 'Saya ingin membuat teman sebanyak mungkin.'),
    (180, 'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya.', 'Saya suka berkirim surat kepada teman-teman saya.'),
    (181, 'Saya suka bermurah hati kepada teman-teman saya.', 'Saya suka mengamati-amati bagaimana perasaan orang lain dalam suatu keadaan tertentu.'),
    (182, 'Saya suka makan di restoran-restoran baru atau asing.', 'Saya suka menempatkan diri saya dalam kedudukan orang lain, dan membayangkan bagaimana perasaan saya bila berada dalam keadaan yang sama.'),
    (183, 'Saya suka bekerja sampai jauh malam untuk menyelesaikan suatu pekerjaan.', 'Saya ingin memahami bagaimana perasaan teman-teman saya dalam menghadapi berbagai masalah.'),
    (184, 'Saya suka nafsu saya terangsang.', 'Saya suka mempelajari dan menganalisa tingkah laku orang-orang lain.'),
    (185, 'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh.', 'Saya suka meramalkan bagaimana teman-teman saya akan bertindak dalam berbagai situasi.'),
    (186, 'Saya suka memaafkan teman-teman saya yang kadang-kadang mungkin menyakiti hati saya.', 'Saya ingin teman-teman saya memberi dorongan kepada saya bila saya mengalami kegagalan.'),
    (187, 'Saya suka bereksperimen dan mencoba hal-hal yang baru.', 'Saya ingin agar teman-teman saya menunjukkan simpati dan pengertian bila saya mengalami kesukaran-kesukaran.'),
    (188, 'Saya suka mengerjakan teka-teki atau memecahkan persoalan-persoalan sampai selesai.', 'Saya ingin diperlakukan dengan ramah oleh teman-teman saya.'),
    (189, 'Saya ingin dianggap mempunyai daya tarik fisik oleh orang-orang dari lawan jenis saya.', 'Saya ingin teman-teman saya banyak menunjukkan rasa sayang mereka terhadap saya.'),
    (190, 'Saya rasanya ingin mengecam seseorang di muka umum bila orang itu memang patut menerimanya.', 'Saya ingin agar teman-teman saya meributkan diri saya apabila saya mendapat cedera atau sakit.'),
    (191, 'Saya suka berlaku sangat ramah terhadap teman-teman saya.', 'Saya ingin dianggap sebagai pemimpin oleh orang-orang lain.'),
    (192, 'Saya lebih suka mencoba pekerjaan-pekerjaan yang baru dan lain daripada terus menerus melakukan pekerjaan yang sama.', 'Bila saya termasuk dalam suatu kepanitian, saya ingin ditunjuk atau dipilih sebagai ketua.'),
    (193, 'Saya ingin mengerjakan sampai selesai setiap pekerjaan ataupun tugas yang telah saya mulai.', 'Saya ingin mampu membujuk dan mempengaruhi orang lain untuk melakukan apa yang saya kehendaki.'),
    (194, 'Saya suka ikut serta dalam diskusi-diskusi tentang sex dan aktivitas sexuil.', 'Saya ingin diminta untuk menyelesaikan perdebatan-perdebatan atau perselisihan-perselisihan antara orang-orang lain.'),
    (195, 'Saya menjadi sedemikian marahnya sehingga rasanya ingin melemparkan dan merusak barang-barang.', 'Saya suka mengatakan kepada orang lain bagaimana mereka harus melakukan pekerjaan mereka.'),
    (196, 'Saya suka berlaku sangat ramah terhadap teman-teman saya.', 'Bila keadaan kurang menguntungkan bagi saya, maka saya merasa bahwa saya harus lebih disalahkan daripada orang-orang lain.'),
    (197, 'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat.', 'Apabila saya melakukan sesuatu yang salah, saya merasa bahwa untuk itu saya harus dihukum.'),
    (198, 'Saya suka bertahan menghadapi suatu pekerjaan atau masalah, sekalipun tampaknya seolah-olah saya tak akan berhasil.', 'Saya merasa bahwa pilu hati dan penderitaan yang telah saya alami lebih banyak membawa kebaikan daripada kerugian bagi saya.'),
    (199, 'Saya suka membaca buku-buku dan sandiwara-sandiwara yang terutama berkisar sekitar soal-soal sex.', 'Saya merasa bahwa saya harus mengakui hal-hal yang telah saya lakukan dan saya anggap tidak baik.'),
    (200, 'Saya rasanya ingin menyalahkan orang lain bila keadaan kurang menguntungkan bagi saya.', 'Saya merasa bahwa saya dalam banyak hal kalah bila dibandingkan dengan orang lain.'),
    (201, 'Saya ingin melakukan setiap pekerjaan sebaik mungkin.', 'Saya suka menolong orang-orang lain yang tidak begitu beruntung seperti saya.'),
    (202, 'Saya suka melakukan hal-hal yang baru dan lain.', 'Saya suka memperlakukan orang-orang lain dengan ramah dan simpatik.'),
    (203, 'Bila saya harus melakukan suatu tugas, saya ingin mengerjakannya sampai selesai.', 'Saya suka menolong orang-orang lain yang tidak begitu beruntung seperti saya.'),
    (204, 'Saya suka bersibuk diri dengan aktivitas-aktivitas sosial bersama-sama dengan orang-orang dari lawan jenis saya.', 'Saya suka memaafkan teman-teman saya yang kadang-kadang mungkin menyakiti hati saya.'),
    (205, 'Saya suka menyerang pendirian-pendirian yang bertentangan dengan pendirian saya.', 'Saya ingin teman-teman saya mempercayai saya dan menceritakan kesulitan-kesulitan mereka kepada saya.'),
    (206, 'Saya suka memperlakukan orang lain dengan ramah dan simpatik.', 'Saya suka bepergian melihat-lihat ke daerah pedalaman.'),
    (207, 'Saya suka mengikuti adat-istiadat dan menghindarkan melakukan hal-hal yang mungkin dianggap tidak wajar oleh orang-orang yang saya hormati.', 'Saya suka mengikuti mode baru.'),
    (208, 'Saya suka bekerja keras pada tiap pekerjaan yang saya hadapi.', 'Saya ingin mengalami hal-hal yang baru dan perubahan-perubahan dalam kehidupan saya sehari-hari.'),
    (209, 'Saya suka mencium orang-orang yang menarik dari lawan jenis saya.', 'Saya suka bereksperimen dan mencoba hal-hal yang baru.'),
    (210, 'Saya rasanya ingin menghardik orang-orang lain bila saya berbeda pendapat dengan mereka.', 'Saya suka mengikuti mode baru.'),
    (211, 'Saya suka menolong orang-orang lain yang tidak begitu beruntung seperti saya.', 'Saya ingin mengerjakan sampai selesai setiap pekerjaan atau tugas yang telah saya mulai.'),
    (212, 'Saya suka berkeliling di pedalaman dan tinggal di berbagai tempat.', 'Saya ingin bekerja berjam-jam tanpa diganggu.'),
    (213, 'Jika saya bepergian, saya ingin segala sesuatunya telah direncanakan terlebih dahulu.', 'Saya suka mengerjakan teka-teki dan memecahkan persoalan-persoalan sampai selesai.'),
    (214, 'Saya suka jatuh cinta pada seseorang dari lawan jenis saya.', 'Saya ingin mengerjakan pekerjaan satu per satu, sebelum memulai yang baru.'),
    (215, 'Saya suka mengatakan kepada orang-orang lain bagaimana pendapat saya mengenai mereka.', 'Saya ingin menghindarkan diganggu bila saya sedang bekerja.'),
    (216, 'Saya suka memberi pertolongan-pertolongan kecil kepada teman-teman saya.', 'Saya suka bersibuk diri dengan aktivitas-aktivitas sosial bersama-sama dengan orang-orang dari lawan jenis saya.'),
    (217, 'Saya suka bertemu dengan orang-orang yang baru.', 'Saya suka mencium orang-orang yang menarik dari lawan jenis saya.'),
    (218, 'Saya ingin mengerjakan teka-teki atau memecahkan persoalan-persoalan sampai selesai.', 'Saya suka jatuh cinta kepada seseorang dari lawan jenis saya.'),
    (219, 'Saya suka berbicara tentang hal-hal yang telah saya capai.', 'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal-soal sex.'),
    (220, 'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh.', 'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar soal-soal sex.'),
    (221, 'Saya ingin teman-teman saya mempercayai saya dan menceritakan kesulitan-kesulitan mereka kepada saya.', 'Saya suka membaca berita-berita surat kabar tentang pembunuhan-pembunuhan dan lain-lain perbuatan kekerasan.'),
    (222, 'Saya suka mengikuti mode baru.', 'Saya rasanya ingin mengecam seseorang di muka umum bila orang itu memang patut menerimanya.'),
    (223, 'Saya ingin menghindarkan diganggu bila saya sedang bekerja.', 'Saya rasanya ingin menghardik orang-orang lain bila saya berbeda pendapat dengan mereka.'),
    (224, 'Saya suka mendengarkan atau menceritakan lelucon-lelucon yang terutama berkisar sekitar soal-soal sex.', 'Saya rasanya ingin membalas dendam bila seseorang menghina saya.'),
    (225, 'Saya suka mengelakkan tanggung jawab dan kewajiban-kewajiban.', 'Saya rasanya ingin memperolok-olok orang-orang yang melakukan hal-hal yang saya anggap bodoh.')
ON CONFLICT (item_no) DO UPDATE SET
    statement_a = EXCLUDED.statement_a,
    statement_b = EXCLUDED.statement_b,
    is_active = TRUE;
