-- V11: Replace the placeholder DISC interpretation scheme with the real
-- 40-pattern classical DISC algorithm ported from
-- "Psikogram DISC_simulasidewi.xlsx" (Psikogram / Sheet3 / Def tabs).
--
-- The old disc_scoring_most/least/dif tables modeled scoring as ONE combined
-- 4-key lookup (d_score,i_score,s_score,c_score) -> single code, which never
-- matched the source spreadsheet and always fell through to a generic
-- "Profil Beragam" fallback. The real algorithm instead:
--   1. Converts each of the 4 raw D/I/S/C tallies independently through a
--      per-line lookup table (disc_most_conversion / disc_least_conversion /
--      disc_dif_conversion below, transcribed from the "Sheet3" tab).
--   2. Classifies the resulting 4 converted values against 40 ordered
--      mutually-exclusive boolean rules (ported in DiscPatternClassifier.java)
--      to get a pattern index 1-40.
--   3. Looks up that index in disc_pattern_profiles (transcribed from the
--      "Def" tab) for the title, trait list, description and job
--      recommendations.
-- This runs three times per result — once each for the MOST, LEAST and DIF
-- lines — matching the Psikogram report's "Kepribadian Saat di Publik",
-- "Kepribadian Saat Mendapat Tekanan" and "Kepribadian Asli / Sesungguhnya"
-- sections.

DROP TABLE IF EXISTS disc_scoring_most;
DROP TABLE IF EXISTS disc_scoring_least;
DROP TABLE IF EXISTS disc_scoring_dif;
DROP TABLE IF EXISTS disc_personality_profiles;

CREATE TABLE disc_most_conversion (
    raw_value INT PRIMARY KEY,   -- 0-20 (clamped beyond range)
    d_conv    NUMERIC(4,2) NOT NULL,
    i_conv    NUMERIC(4,2) NOT NULL,
    s_conv    NUMERIC(4,2) NOT NULL,
    c_conv    NUMERIC(4,2) NOT NULL
);

CREATE TABLE disc_least_conversion (
    raw_value INT PRIMARY KEY,   -- 0-20 (clamped beyond range)
    d_conv    NUMERIC(4,2) NOT NULL,
    i_conv    NUMERIC(4,2) NOT NULL,
    s_conv    NUMERIC(4,2) NOT NULL,
    c_conv    NUMERIC(4,2) NOT NULL
);

CREATE TABLE disc_dif_conversion (
    raw_value INT PRIMARY KEY,   -- -22 to 22 (clamped beyond range)
    d_conv    NUMERIC(4,2) NOT NULL,
    i_conv    NUMERIC(4,2) NOT NULL,
    s_conv    NUMERIC(4,2) NOT NULL,
    c_conv    NUMERIC(4,2) NOT NULL
);

-- pattern_index (1-40) is what DiscPatternClassifier resolves to; type_key is
-- the classic DISC notation (e.g. "D / I-D") kept for reference/admin display.
CREATE TABLE disc_pattern_profiles (
    id                  BIGSERIAL PRIMARY KEY,
    pattern_index       INT UNIQUE NOT NULL,
    type_key            VARCHAR(30) NOT NULL,
    title               VARCHAR(100) NOT NULL,
    traits              JSONB NOT NULL,        -- ordered array of trait phrases
    description         TEXT NOT NULL,
    job_recommendations TEXT NOT NULL
);

-- disc_results: add the 3 lookups the report needs. profile_title/profile_desc
-- (already in the table since V2) are repurposed to hold the DIF/"real
-- personality" profile — the headline result — so only MOST/LEAST plus DIF's
-- traits and job recommendations need new columns.
ALTER TABLE disc_results
    ADD COLUMN most_profile_title   VARCHAR(100),
    ADD COLUMN most_profile_traits  JSONB,
    ADD COLUMN least_profile_title  VARCHAR(100),
    ADD COLUMN least_profile_traits JSONB,
    ADD COLUMN dif_profile_traits   JSONB,
    ADD COLUMN job_recommendations  TEXT;

-- most_key/least_key/dif_key held the old scheme's short codes (VARCHAR(10),
-- e.g. "DI"); real type_keys like "D / S-D-C / S-C-D" run longer.
ALTER TABLE disc_results
    ALTER COLUMN most_key TYPE VARCHAR(30),
    ALTER COLUMN least_key TYPE VARCHAR(30),
    ALTER COLUMN dif_key TYPE VARCHAR(30);

-- Existing rows were produced by the old placeholder logic (mostly the
-- generic "Profil Beragam" fallback) — dev-only data, safe to clear so every
-- remaining result reflects the real algorithm.
TRUNCATE TABLE disc_results RESTART IDENTITY;

INSERT INTO disc_most_conversion (raw_value, d_conv, i_conv, s_conv, c_conv) VALUES
  (0, -6.0, -7.0, -5.7, -6.0),
  (1, -5.3, -4.6, -4.3, -4.7),
  (2, -4.0, -2.5, -3.5, -3.5),
  (3, -2.5, -1.3, -1.5, -1.5),
  (4, -1.7, 1.0, -0.7, 0.5),
  (5, -1.3, 3.0, 0.5, 2.0),
  (6, 0.0, 3.5, 1.0, 3.0),
  (7, 0.5, 5.3, 2.5, 5.3),
  (8, 1.0, 5.7, 3.0, 5.7),
  (9, 2.0, 6.0, 4.0, 6.0),
  (10, 3.0, 6.5, 4.6, 6.3),
  (11, 3.5, 7.0, 5.0, 6.5),
  (12, 4.0, 7.0, 5.7, 6.7),
  (13, 4.7, 7.0, 6.0, 7.0),
  (14, 5.3, 7.0, 6.5, 7.3),
  (15, 6.5, 7.0, 6.5, 7.3),
  (16, 7.0, 7.5, 7.0, 7.3),
  (17, 7.0, 7.5, 7.0, 7.5),
  (18, 7.0, 7.5, 7.0, 8.0),
  (19, 7.5, 7.5, 7.5, 8.0),
  (20, 7.5, 8.0, 7.5, 8.0);

INSERT INTO disc_least_conversion (raw_value, d_conv, i_conv, s_conv, c_conv) VALUES
  (0, 7.5, 7.0, 7.5, 7.5),
  (1, 6.5, 6.0, 7.0, 7.0),
  (2, 4.3, 4.0, 6.0, 5.6),
  (3, 2.5, 2.5, 4.0, 4.0),
  (4, 1.5, 0.5, 2.5, 2.5),
  (5, 0.5, 0.0, 1.5, 1.5),
  (6, 0.0, -2.0, 0.5, 0.5),
  (7, -1.3, -3.5, -1.3, 0.0),
  (8, -1.5, -4.3, -2.0, -1.3),
  (9, -2.5, -5.3, -3.0, -2.5),
  (10, -3.0, -6.0, -4.3, -3.5),
  (11, -3.5, -6.5, -5.3, -5.3),
  (12, -4.3, -7.0, -6.0, -5.7),
  (13, -5.3, -7.2, -6.5, -6.0),
  (14, -5.7, -7.2, -6.7, -6.5),
  (15, -6.0, -7.2, -6.7, -7.0),
  (16, -6.5, -7.3, -7.0, -7.3),
  (17, 6.7, -7.3, -7.2, -7.5),
  (18, 7.0, -7.3, -7.3, -7.7),
  (19, -7.3, -7.5, -7.5, -7.9),
  (20, -7.5, -8.0, -8.0, -8.0);

INSERT INTO disc_dif_conversion (raw_value, d_conv, i_conv, s_conv, c_conv) VALUES
  (-22, -8.0, -8.0, -8.0, -7.5),
  (-21, -7.5, -8.0, -8.0, -7.3),
  (-20, -7.0, -8.0, -8.0, -7.3),
  (-19, -6.8, -8.0, -8.0, -7.0),
  (-18, -6.75, -7.0, -7.5, -6.7),
  (-17, -6.7, -6.7, -7.3, -6.7),
  (-16, -6.5, -6.7, -7.3, -6.7),
  (-15, -6.3, -6.7, -7.0, -6.5),
  (-14, -6.1, -6.7, -6.5, -6.3),
  (-13, -5.9, -6.7, -6.5, -6.0),
  (-12, -5.7, -6.7, -6.5, -5.85),
  (-11, -5.3, -6.7, -6.5, -5.85),
  (-10, -4.3, -6.5, -6.0, -5.7),
  (-9, -3.5, -6.0, -4.7, -4.7),
  (-8, -3.25, -5.7, -4.3, -4.3),
  (-7, -3.0, -4.7, -3.5, -3.5),
  (-6, -2.75, -4.3, -3.0, -3.0),
  (-5, -2.5, -3.5, -2.0, -2.5),
  (-4, -1.5, -3.0, -1.5, -0.5),
  (-3, -1.0, -2.0, -1.0, 0.0),
  (-2, -0.5, -1.5, -0.5, 0.3),
  (-1, -0.25, 0.0, 0.0, 0.5),
  (0, 0.0, 0.5, 1.0, 1.5),
  (1, 0.5, 1.0, 1.5, 3.0),
  (2, 0.7, 1.5, 2.0, 4.0),
  (3, 1.0, 3.0, 3.0, 4.3),
  (4, 1.3, 4.0, 3.5, 5.5),
  (5, 1.5, 4.3, 4.0, 5.7),
  (6, 2.0, 5.0, 4.35, 6.0),
  (7, 2.5, 5.5, 4.7, 6.3),
  (8, 3.5, 6.5, 5.0, 6.5),
  (9, 4.0, 6.7, 5.5, 6.7),
  (10, 4.7, 7.0, 6.0, 7.0),
  (11, 4.85, 7.3, 6.2, 7.3),
  (12, 5.0, 7.3, 6.3, 7.3),
  (13, 5.5, 7.3, 6.5, 7.3),
  (14, 6.0, 7.3, 6.7, 7.3),
  (15, 6.3, 7.3, 7.0, 7.3),
  (16, 6.5, 7.3, 7.3, 7.3),
  (17, 6.7, 7.3, 7.3, 7.5),
  (18, 7.0, 7.5, 7.3, 8.0),
  (19, 7.3, 8.0, 7.3, 8.0),
  (20, 7.3, 8.0, 7.5, 8.0),
  (21, 7.5, 8.0, 8.0, 8.0),
  (22, 8.0, 8.0, 8.0, 8.0);
INSERT INTO disc_pattern_profiles (pattern_index, type_key, title, traits, description, job_recommendations) VALUES
  (1, 'C', 'LOGICAL THINKER', '["Pendiam", "Anti Kritik", "Perfeksionis", "Cenderung Santai", "Detail", "Empati", "Rapi", "Organized", "Kaku pada Metode & Prosedur"]'::jsonb, 'Seorang yang praktis, cakap dan unik. Ia orang yang mampu menilai diri sendiri dan kritis terhadap dirinya dan orang lain. Ia menyukai hal yang detil dan logis; secara alamiah ia sangat analitis. Karena menyimpan informasi, ia meneliti isu berulang-ulang kali. Ia cenderung malu dan tertutup; ia hati-hati dalam membuat keputusan yang berdasarkan pada logika, bukan emosi, selalu menggunakan pertanyaan "bagaimana dan mengapa". Ia mengerjakan sesuatu dengan sistematis dan akurat. Ia rapi dan terorganisir sebab ia merasa bahwa keadaan berantakan sama dengan mutu yang rendah; demikian juga, rapi dan teratur merupakan mutu yang tinggi. Sangat teliti dalam segala sesuatu seperti halnya dalam pekerjaan dan penggunaan waktunya. Ia merencanakan dan mengorganisir semua sisi kehidupannya. Kelambanan sangat mengganggunya dan tak dapat ditolerir.', 'Planner (any function), Engineer (Installation, Technical), Technical/Research (Chemist Technician), Academic, Statistician, Government Worker, IT Management, Prison Officer, Quality Controller.'),
  (2, 'D', 'ESTABLISHER', '["Individualis", "Ego Tinggi, Kurang Sensitif", "Kurang Pertimbangan", "Efektif", "High Motivation", "Bersemangat Tinggi", "Percaya Diri, cenderung Nekat", "Kreatif", "Terlalu Dominan", "Agresif", "Terlalu Dinamis", "Penuh Ambisi"]'::jsonb, 'Memiliki rasa ego yang tinggi dan cenderung invidualis dengan standard yang sangat tinggi. Ia lebih suka menganalisa masalah sendirian daripada bersama orang lain. Rasa egoisnya yang kuat membuatnya tidak nyaman di bawah kendali orang lain; ia lebih suka menjadi "boss" dan menetapkan standard tinggi baik untuk dirinya maupun orang lain. Ia menghindari sesuatu yang biasa-biasa dan cenderung mencari tantangan yang baru. Ia menyukai petualangan dan kadang-kadang beralih ke dalam petualangan baru sebelum mempertimbangkannya secara menyeluruh. Mampu memimpin situasi dan orang lain dalam rangka mencapai sasarannya; ia ingin selalu unggul dalam persaingan dengan taruhan apapun.', 'Attorney, Researcher, Sales Representative, Planning Consultant, Transport Personnel, Production (Director, Manager, Supervisor), Technologist, Strategic Planning, Trouble Shooting, Marketing Services, Consultant, Engineering (Director, Manager, Supervisor) and Self-Employment.'),
  (3, 'D / C-D', 'DESIGNER', '["Sensitif", "Kurang Cepat", "Anti Tekanan", "Terlalu Mandiri", "Kurang Percaya Orang Lain", "Anti Kritik", "Dingin", "Kreatif", "Result Oriented", "Suka Tantangan"]'::jsonb, 'Seorang yang sangat berorientasi pada tugas dan sensitif pada permasalahan. Ia lebih mempedulikan tugas yang ada dibanding orang-orang di sekitarnya, termasuk perasaan mereka. Sangat kukuh/keras dan mempunyai pendekatan yang efektif dalam pemecahan masalah. Oleh karena sifat alamiah dan keinginannya akan hasil yang terukur, Akan tampak dingin, tidak berperasaan dan menjaga jarak. Ia membuat keputusan berdasar pada fakta, bukan emosi. Cenderung pendiam dan tidak mudah percaya.', 'Engineering (Management, Research, Design), Research (R&D), Planning, Chemist, Accountancy, Specialist, Finance, Technician, Quality Control, Production Planning/Management, Design Engineer, Bookkeeper, Chemist Technician, Safety Officer, Librarian.'),
  (4, 'D / I-D', 'NEGOTIATOR', '["Suka Bergaul", "Anti Rutin", "Aktif", "Terlalu Percaya Diri", "Agresif", "Optimis", "Kurang Detail", "Result Oriented"]'::jsonb, 'Merupakan seorang pemimpin integratif yang bekerja dengan dan melalui orang lain.  Ia ramah, memiliki perhatian yang tinggi akan orang dan juga mempunyai kemampuan untuk memperoleh hormat dan penghargaan dari berbagai tipe orang.  Melakukan pekerjaannya dengan cara yang bersahabat, baik dalam mencapai sasarannya maupun meyakinkan pandangannya kepada orang lain.  Ia tidak begitu memperhatikan hal-hal kecil.  Kadang bertindak sesuai dengan kata hati/impulsif, terlalu antusias dan sangat banyak bicara.  Ia terlalu berlebihan menilai kemampuannya dalam memotivasi atau mengubah perilaku orang lain.  Mencari kebebasan dari rutinitas, menginginkan otoritas/wewenang dan juga prestise.  Ia menginginkan aktivitas yang bervariasi dan bekerja lebih efisien jika data-data analitis disediakan oleh orang lain.  Menginginkan penugasan yang mengutamakan mobilitas dan tantangan.', 'Sales and Marketing (Directing, Manager, Person), Public Relations, Recruitment Consultant, Politician, Director, Self-Employed, Hotelier, Travel Agent, Trainer, Hospitality, Lawyer, Solicitor, Motivators, Team Leader, Politician, Trainer, Lecturer, Theatrical Agent, General Management and Leading People, Attorney.'),
  (5, 'D / I-D-C', 'CONFIDENT & DETERMINED', '["Pandai Memilih Orang", "Leader", "Good Interpersonal Skill", "Dominan", "Agresif", "Perfeksionis", "Good Communication Skill", "Aktif", "Need Recognition n Reward", "Kurang Peduli pada Aturan", "Terburu-buru"]'::jsonb, 'Sangat berorientasi terhadap tugas dan juga menyukai orang.  Ia sangat baik dalam menarik orang/recruiting.  Seorang yang bersahabat, tetapi menyukai keadaan di mana tugas-tugas harus dilakukan dengan benar.  Ia kadang-kadang tampak dingin dan mendominasi.  Ia juga bisa sangat fokus pada tugas dan melupakan orang-orang di sekitarnya.  Sangat mengharapkan orang-orang terlibat dalam proyeknya, tetapi tidak memperdulikan apa yang diinginkan oleh orang-orang itu.  Ia perlu mendengar dan memikirkan  apa yang menjadi keinginan orang di sekitarnya, khususnya kesempatan untuk mencoba.  Ia sangat membutuhkan persetujuan sosial seperti halnya ia sangat mempercayai orang lain.  Karena itu, ia kadang-kadang berlebihan dalam menilai orang dan kemampuannya.  Ia tampak tidak konsisten dan tidak karuan karena ketidakmampuannya berkonsentrasi dan fokus dalam waktu yang lama.  Perlu belajar untuk secara sungguh-sungguh mendengarkan orang-orang di sekitarnya dari pada selalu berpikir apa yang ingin dikatakan.  Ia mempunyai kemampuan logika yang tinggi ketika ia mau menggunakannya.', 'Specialist/Technical Selling (Computer, Finance, Engineer and others, Chef, Technical/Capital Equipment Selling), Financial (Manager, Specialist), Computer Hardware Sales, Engineering (Manager, Designer, Buyer, Draughtsman), Project Engineer, Sales Engineer, Consultant, Trainer, Lecturer, Hotelier, Insurance, Mortgage and Finance Sales, Teacher, Travel Agent, Personnel and Marketing Services.'),
  (6, 'D / I-D-S', 'REFORMER', '["Mudah Bergaul", "Leader", "Sadar Diri", "Butuh Pujian & Penghargaan", "Cepat Percaya Orang", "Mudah Simpati & Empati", "Motivator", "Optimis & Positif", "Anti Aturan", "Kurang Detail", "Terlalu Selektif"]'::jsonb, 'Seorang yang bersahabat dan sosial; ia juga suka mengendalikan situasi dan menjadi pemimpin.  Ia menyelesaikan tugasnya melalui keterampilan sosialnya; ia peduli dan menerima orang lain.  Ia berkonsentrasi pada tugas yang ada di tangannya sampai selesai dan akan minta bantuan orang lain jika perlu.  Ia menyadari keterbatasannya dan meminta bantuan jika memerlukannya.  Ia disukai dan orang ingin menolongnya.  Senang membagi kebanggaannya dengan kelompok; ia seorang team player tetapi juga team leader.  Menginginkan popularitas dan pengakuan.', 'Hotelier, Customer Service, Complaints Manager, Recruiting Agent, Sales (Manager/Person), Marketing Services, Public Relations, Politician, Computer Software Sales, Lecturer, Engineering and Production (Manager/Supervisor).'),
  (7, 'D / I-S-D', 'MOTIVATOR', '["Leader (Kelompok Kecil)", "Supporter", "Sosialisasi Baik", "Butuh Ketegasan", "Butuh Pujian & Penghargaan", "Kurang Detail", "Agak Kaku"]'::jsonb, 'Seorang yang menampilkan gaya bersemangat ketika termotivasi pada sasaran.  Ia lebih suka memimpin atau melibatkan diri, walaupun ia juga mau melayani sebagai pembantu.  Ia membutuhkan pengakuan dan penghargaan serta senang pada peran pendukung.  Ia peduli kepada orang-orang di sekitarnya dan akan mempertimbangkan perasaan orang lain dalam proses pengambilan keputusan.  Menampilkan keterampilan berhubungan dan berkomunikasi dengan sangat baik.  Ia akan berusaha keras menyelesaikan tugas dengan cepat dan efisien.', 'Hotelier, Community Counseling, Customer Service, Complaints Manager, Community Work, Recruitment Consultant, Hospitality, Teacher, Telemarketing, Production Manager, Complaints Manager, Recruiting Agent, Sales (Manager/Person), Marketing Services, Public Relations, Politician, Call Centre Manager, Lecturer, Engineering and Production (Manager/Supervisor).'),
  (8, 'D / S-D-C / S-C-D', 'INQUIRER', '["Full Self Control", "Sabar", "Penuh Pertimbangan", "Good Interpersonal", "Selektif", "Lambat Adaptasi", "Inisiatif kurang", "Result Oriented", "Kaku dan Keras Kepala", "Good Service", "Kurang dlm hal Managerial"]'::jsonb, 'Seorang yang sabar, terkontrol dan suka menggali fakta dan jalan keluar.  Ia tenang dan ramah.  Ia merencanakan pekerjaan dengan hati-hati, tetapi agresif, menanyakan sesuatu serta mengumpulkan data pendukung.  Kemudian ia bekerja dengan konsisten dengan arahan yang benar.  Menjadi individu yang penuh perhatian, rendah hati, dan ia berhubungan baik dengan hampir semua orang.  Seorang yang konsisten dan suka menolong. People skill darinya melebihi orientasi tugasnya.', 'Directing, Managing or Supervising (in Engineering, Accountancy, Research and Development and Computing disciplines), Research Manager, Scientific Work, Accountant, Administration, Project Engineer, Draughtsman, Designer, Analyst, Finance, Chemist, Technical Service Support, Flight Attendant, Technician, Service Engineer, Service Manager, Security Specialist.'),
  (9, 'D-I', 'PENGAMBIL KEPUTUSAN', '["Pekerja Keras", "Leader", "Banyak Minat", "Dingin / Task Oriented", "Kurang Pergaulan", "Kontrol Emosi Kurang", "Suka Tantangan", "Cepat Bosan", "Anti Aturan", "Kurang Detail", "Kurang Peduli Wewenang", "Argumentatif"]'::jsonb, 'Tidak basa-basi dan tegas, ia cenderung merupakan seorang invidualis yang kuat. Ia berpandangan jauh ke depan, progresif dan mau berkompetisi untuk mencapai sasaran. DI seorang yang selalu ingin tahu dan mempunyai minat dengan cakupan yang luas. Ia seorang yang logis, kritis dan tajam dalam memecahkan masalah. Sering kali ia tampak imajinatif. Ia mempunyai kemampuan memimpinan yang baik. Ia kadang tampak keras kepala atau dingin karena orientasi dan prioritasnya pada tugas cenderung melebihi orientasi terhadap sesama. Ia mencanangkan standard tinggi pada dirinya dan akan sangat kritis ketika standard ini tidak dicapai. Ia juga menempatkan standard tinggi pada orang-orang di sekitarnya, serta mengutamakan kesempurnaan. Ia menginginkan otoritas yang jelas dan menyukai tugas-tugas baru.', 'General Management (Directing/Managing/Supervising, Public Relations, Business Management, Conflict Resolution, Industrial Relations, Business Consultant, Trouble Shooting, Sales and Sales Management, Marketing, Promoting, Production (Director, Manager, Supervisor), Consultancy, Publishing, Sales Executive, Promotional Work, Brokers, Self-Employment, Advertising, Lecturing, Dealing/Broking.'),
  (10, 'D-I-S', 'DIRECTOR', '["Pengelola", "Enerjik", "Kurang Detail", "Mudah Bosan", "Agresif", "Arogan", "Kurang Focus"]'::jsonb, 'Fokus pada penyelesaian pekerjaan dan menunjukkan penghargaan yang tinggi kepada orang lain.  Ia memiliki kemampuan untuk menggerakkan orang dan pekerjaan dikarenakan keterampilannya berpikir ke depan dan hubungan antar manusia.  Tidak berorientasi detil, ia fokus pada target secara keseluruhan dengan menyerahkan hal detil kepada orang lain.  Enerjik dan sosial, ia mampu memotivasi orang lain sambil menyelesaikan pekerjaannya.  Ia menampilkan rasa percaya diri dan mampu meyakinkan orang lain.  Sekali ia memutuskan sesuatu, ia akan terus mengerjakannya dan bertahan sampai selesai.', 'Engineering and Production (Directing, Managing, Supervising), Sales, Sales Management, Service Manager, Distribution, Public Relations, Office Management, Account Manager, Customer Service, Retail Manager, IT, Lecturer, Logistics, Manager-General, National Accounts Manager, Teacher, Projects Manager.'),
  (11, 'D-S', 'SELF-MOTIVATED', '["Objektif & Analitis", "Mandiri", "Good Planner", "Komitmen thd Target", "Menghindari Konflik"]'::jsonb, 'Seorang yang obyektif dan analitis.  Ia ingin terlibat dalam situasi, dan ia juga ingin memberikan bantuan dan dukungan kepada orang yang ia hormati.  Secara internal termotivasi oleh target pribadi, ia berorientasi terhadap pekerjaannya tapi juga menyukai hubungan dengan sesama.  Karena determinasinya yang kuat, ia sering berhasil dalam berbagai hal; karakternya yang tenang, stabil dan daya tahannya yang tinggi memiliki kontribusi dalam keberhasilannya.  Ulet dalam memulai pekerjaan. Ia akan berusaha keras untuk mencapai sasarannya.  Seorang yang mandiri dan cermat serta memiliki tindak lanjut yang baik.', 'Engineering and Production (Directing, Managing, Supervising), Project Management, Researcher, Chemist (R&D), Planner, Engineering (R&D), Systems Analyst, Commercial Planner, Computer Engineer, Programmer, IT, Other computer-related disciplines, Technical Trouble Shooting and Directing, Lawyer, Solicitor, Development Engineer, Work Study, Barrister, Attorney.'),
  (12, 'I / C-I-S', 'MEDIATOR', '["Loyal", "Tight Scheduled", "Curious", "Sensitif", "Good Communication Skill", "Good Analitical Think", "Good Interpersonal Skill", "Cepat Beradaptasi", "Anti Kritik", "Not Leader", "Work/Play Conflict"]'::jsonb, 'Merupakan individu yang berorientasi pada orang, ia mampu menggabungkan ketepatan dan loyalitas.  Ia cenderung peka dan mempunyai standard yang tinggi.  Ia menginginkan stabilitas dan berorientasi terhadap sasaran.  Ia menginginkan pengakuan sosial dan perhatian pribadi.  Ia bersahabat, antusias, informal, banyak bicara, dan mungkin sangat mencemaskan apa yang dipikirkan oleh orang lain.  Ia menolak agresi, dan mengharapkan suasana harmonis.  Ia cenderung cukup cerdas dalam berbagai hal. Ia merupakan pencari fakta yang sangat baik dan akan membuat keputusan yang baik setelah mengumpulkan fakta dan data pendukung.', 'Engineering and Production (Supervisor, Installer, Technician, Service and Design), Research (Supervisor, Chemist, Lab. Technician), Trainer, Finance (Supervisor, Accountant, Advisor), Public Relations, Administration, Office Administrator, Market Analyst, System Analyst, Programmer, Selling (Technical/Service).'),
  (13, 'I / C-S-I', 'PRACTITIONER', '["Perfeksionis", "Quality Oriented", "Scheduled", "Anti Kejutan", "Good Interpersonal Skill", "Terlalu Detail", "Sistematis", "Kaku / Tidak fleksibel", "Monoton"]'::jsonb, 'Merupakan individu yang berorientasi pada orang, ia mampu menggabungkan ketepatan dan loyalitas.  Ia cenderung peka dan mempunyai standard yang tinggi.  Ia menginginkan stabilitas dan berorientasi terhadap sasaran.  Ia menginginkan pengakuan sosial dan perhatian pribadi.  Bersahabat, antusias, informal, banyak bicara, dan mungkin sangat mencemaskan apa yang dipikirkan oleh orang lain.  Ia menolak agresi dan mengharapkan suasana harmonis.  Ia cenderung cukup cerdas dalam berbagai hal. Ia merupakan pencari fakta yang sangat baik dan akan membuat keputusan yang baik setelah mengumpulkan fakta dan data pendukung.', 'Engineering and Production (Supervisor, Installer, Technician, Service and Design), Research (Supervisor, Chemist), Trainer, Finance (Manager, Supervisor, Accountant, Advisor), Public Relations-Administration, Purchasing, Chemist Research, Office Administrator, Computer Programmer, Market Analyst, System Analyst, Programmer, Research and Development Supervisor, Laboratory Technician, Legal, Selling (Technical/Service).'),
  (14, 'I-S-C / I-C-S', 'RESPONSIVE & THOUGHTFUL', '["High Energy", "Good Communication Skill", "To The Point", "Sensitif", "Banyak Bicara", "Need Recognation", "Need Socialism", "Anti thd Kritik", "Terlalu banyak bersosialisasi", "Leadership kurang", "Kurang Fokus", "Anti Deadline"]'::jsonb, 'Merupakan individu yang berorientasi pada orang dan lancar berkomunikasi serta loyal.  Ia cenderung sensitif dan mempunyai standard yang tinggi.  Keputusannya dibuat berdasarkan fakta dan data pendukung.  Ia sepertinya tidak bisa diam.  Ia perlu untuk lebih terus terang dan jangan terlalu subyektif.  Ia butuh pengakuan sosial dan perhatian pribadi; ia dapat cepat akrab dengan orang lain.  Ia bersahabat, antusias, informal, banyak bicara dan terlalu khawatir terhadap apa yang dipikirkan orang.  Ia menguasai banyak hal.  Ia ingin diterima sebagai anggota kelompok dan ingin mengetahui secara pasti apa yang diharapkan darinya sebelum ia memulai proyek baru.', 'Actors, Chef, Personnel, Welfare, Broadcasting, Training, Attorney, Teaching, Accounting, Technical Instructor, Accounting-General, Accounts Supervisor, Customer Services, Public Relations, Artist, Hotelier, Demonstrator, Florist/Floral Designer, Engineering (Sales, Service, Project, Draughtsman, Designer), Graphic Designer, Specialist (Soft/Services), Selling, Purchasing, Singers, Technical Instructor, Personnel Management, Politician, Supervising (Engineering, Production, Accounts), Administration Work, Sales Engineer, Secretarial, Industrial Relations Specialist.'),
  (15, 'S', 'SPECIALIST', '["Stabil & Konsisten", "Terkendali", "Nyaman di Belakang Layar", "Sabar", "Loyal", "Sulit Adaptasi", "Process Oriented", "Teguh", "Need for Peace", "Anti Perubahan", "Sulit Menentukan Prioritas"]'::jsonb, 'Merupakan individu konsisten yang berusaha menjaga lingkungan/suasana yang tidak berubah.  Ia bekerja dengan baik bersama orang-orang dengan berbagai kepribadian karena perilakunya yang terkendali dan rendah hati.  Sabar, loyal dan suka menolong.  Persahabatan dikembangkannya dengan lambat dan selektif.  Ia tidak bosan dengan rutinitas dan sangat baik bekerja dengan petunjuk dan peraturan yang jelas. Ia mengharapkan bantuan dan supervisi pada saat mengawali proyek baru.  Ia butuh waktu untuk menyesuaikan diri dengan perubahan dan sungkan menjalankan "cara-cara lama mengerjakan sesuatu".  Ia akan menghindari konfrontasi dan berusaha sekuat tenaga memendam perasaannya.', 'Administrative Work, Engineering and Production areas (Sales, Services, Project, Painter, Plumber, Draughtsman, Designer, Operative), Chef, Accounting, Telemarketing/Tele-Sales, Research and Development, Administrator, Florist/Floral Designer, Retail-General, Sales-General, Accounting-General, Service-General, Landscape Gardener.'),
  (16, 'S / C-S', 'PERFECTIONIST', '["Detail & Teliti", "Butuh Situasi Stabil", "Sistematik & Prosedural", "Menghindari Konflik", "Anti Kritik", "Lambat Memutuskan", "Sulit Adaptasi", "Pendendam", "Anti Perubahan"]'::jsonb, 'Berpikir sistematis dan cenderung mengikuti prosedur dalam kehidupan pribadi dan pekerjaannya.  Teratur dan memiliki perencanaan yang baik, ia teliti dan fokus pada detil.  Bertindak dengan penuh kebijaksanaan, diplomatis dan jarang menentang rekan kerjanya dengan sengaja.  Ia sangat berhati-hati, sungguh-sungguh mengharapkan akurasi dan standard tinggi dalam pekerjaannya.  Ia cenderung terjebak dalam hal detil, khususnya jika harus memutuskan.  Menginginkan adanya petunjuk standard pelaksanaan kerja dan tanpa perubahan mendadak.', 'Researcher (Technician, Chemist, Quality Control), Engineer (Project, Draughtsman, Armed Forces, Designer), Statistician, Surveyor, Optician, Medical Specialist, Health Care, IT Management, Planner, Technical Writing, Production, Dentist, Quality Control, Planning, Dental Technician, Accounting, Computer Programmer, Psychologist, Surgeon, Architect, Medical Specialist.'),
  (17, 'S-C', 'PEACEMAKER, RESPECTFULL & ACCURATE', '["Sulit Beradaptasi", "Anti Kritik", "Pendendam", "Sukar Berubah", "Detail", "Empati", "Memikirkan Dampak ke Orang Lain", "Terlalu Mendalam dalam Berpikir", "Concern ke Data dan Fakta", "Introvert", "Loyal"]'::jsonb, 'Ia adalah orang yang baik secara alamiah dan sangat berorientasi detil.  Ia peduli dengan orang-orang di sekitarnya dan mempunyai kualitas yang membuatnya sangat teliti dalam penyelesaian tugas.  Ia mempertimbangkan sekelilingnya dengan hati-hati sebelum membuat keputusan untuk melihat pengaruhnya pada mereka; saat tertentu ia terlalu hati-hati.  Jika ia merasa seseorang memanfaatkan situasi, ia akan memperlambat kerjanya sehingga dapat mengamati apa yang sedang berlangsung di sekitarnya.', 'Office (Manager, Supervisor, Person), Chief Clerk, General Administrator, Production Supervisor, Planner, Accountant, Research and Development, Flight Attendant, Engineering (Project Manager, Supervisor, Technician), Computer Programmer, Draughtsman, Soft/Service Selling, Doctor, Cashier, Receptionist, Data Entry, Planner, Word Processing, Property Manager, Database Administrator, Health Care, Statistician, Nursing-Administration, Company Secretary, System Analyst, Programmer, Statistician, Accounting-General, Security Specialist.'),
  (18, 'D-C', 'CHALLENGER', '["Seorang yang tekun", "Sensitif terhadap permasalahan", "Mempunyai keputusan yang kuat", "Kreatif  dalam memecahkan masalah", "Memiliki reaksi yang cepat", "Mampu mencari solusi permasalahan", "Banyak memberikan ide-ide.", "Usaha yang keras pada ketepatan", "Cenderung perfeksionis"]'::jsonb, 'Seorang yang sensitif terhadap permasalahan, dan memiliki kreativitas yang baik dalam memecahkan masalah. Ia dapat menyelesaikan tugas-tugas penting dalam waktu singkat karena mempunyai keputusan yang kuat. Seorang yang tekun dan memiliki reaksi yang cepat.  Ia akan meneliti dan mengejar semua kemungkinan yang ada dalam mencari solusi permasalahan.  Ia banyak memberikan ide-ide dengan berfokus pada pekerjaan. Usaha yang keras pada ketepatan akan mengimbangi keinginannya pada hasil yang terukur.  Ia cenderung perfeksionis dan dapat juga memperlambat pengambilan keputusan karena keinginannya untuk menentukan pilihan yang terbaik.', 'Engineering (Management, Research, Design), Actuaries, Research (R&D), Planning, Chemist, Hospital Supervisor, Industrial Marketing, Investment Banking, Medical Administrator, Mortgage Brokers, Accountancy, Fund Management, Specialist Finance, Quality Control and Specialist work in any area where knowledge and experience is available, Production, Financial Services, Technical Management, Project Leader, Matron, Strategic Planning, Industrial Marketing.'),
  (19, 'D-I-C', 'CHANCELLOR', '["Seorang yang ramah secara alami", "Menggabungkan kesenangan dengan pekerjaan", "Menyukai hubungan dengan sesama", "Menikmati interaksi dengan sesama", "Dapat mengerjakan hal-hal detil", "Ingin melakukan segala sesuatu dengan tepat", "Menilai orang dan tugas secara hati-hati", "Sering melalaikan perencanaan yang seksama", "Mudah beralih kepada proyek-proyek baru"]'::jsonb, 'Ia menggabungkan antara kesenangan dengan pekerjaan/bisnis ketika melakukan sesuatu. Ia kelihatan menyukai hubungan dengan sesama tetapi juga dapat mengerjakan hal-hal detil. Ia ingin melakukan segala sesuatu dengan tepat, dan ia akan menyelesaikan tugasnya untuk meyakinkan ketepatan dan kelengkapannya. Seorang yang ramah secara alami dan menikmati interaksi dengan sesama, akan tetapi ia akan juga menilai orang dan tugas secara hati-hati; persahabatannya akan bergeser sesuai dengan dorongan hatinya pada orang lain di sekitarnya. Ia sering melalaikan perencanaan yang seksama dan akan beralih ke pada proyek-proyek baru tanpa pertimbangan yang menyeluruh.', 'Technical/Scientific (Directing, Management, Supervision), Engineering, Finance, Production Planning, Personnel Disciplines, Self-Employment, Credit Manager, Planner, Fund Management, Computer Hardware/Software Sales, IT, Business Consultant, Banking, Logistics, Lecturing, Work Study, Film Director, Transport, Consultancy, Industrial Relations and Computers (Selling, Software, Systems Analyst) and General Manager.'),
  (20, 'D-S-I', 'DIRECTOR', '["Seorang yang obyektif dan analitis", "Ingin terlibat dalam situasi", "Ingin memberikan bantuan dan dukungan", "Termotivasi oleh target pribadi", "Berorientasi terhadap pekerjaannya", "Menyukai hubungan dengan sesama", "Mempunyai determinasi yang kuat", "Karakternya tenang", "Stabil dan daya tahannya tinggi", "Ulet dalam memulai pekerjaan", "Berusaha keras mencapai sasarannya", "Mandiri dan cermat"]'::jsonb, 'Seorang yang obyektif dan analitis.  Ia ingin terlibat dalam situasi, dan ia juga ingin memberikan bantuan dan dukungan kepada orang yang ia hormati.  Secara internal termotivasi oleh target pribadi, ia berorientasi terhadap pekerjaannya tapi juga menyukai hubungan dengan sesama.  Karena determinasinya yang kuat, ia sering berhasil dalam berbagai hal; karakternya yang tenang, stabil dan daya tahannya yang tinggi memiliki kontribusi dalam keberhasilannya.  Ulet dalam memulai pekerjaan. Ia akan berusaha keras untuk mencapai sasarannya.  Seorang yang mandiri dan cermat serta memiliki tindak lanjut yang baik.', 'Engineering and Production (Directing, Managing, Supervising), Sales, Sales Management, Service Manager, Distribution, Public Relations, Creative Designer, Office Management, Chief Engineer, Business Consultant, Chief Financial Officer, Customer Service, National Accounts Manager, Chief Accountant, Lecturer, Projects Manager, Research Planning, Human Resources, Scientific Work, Security Specialist, Solicitor, Planner, Production Administrator.'),
  (21, 'D-S-C', 'Director', '["Seorang yang obyektif dan analitis", "Ingin terlibat dalam situasi", "Ingin memberikan bantuan dan dukungan", "Termotivasi oleh target pribadi", "Berorientasi terhadap pekerjaannya", "Menyukai hubungan dengan sesama", "Mempunyai determinasi yang kuat", "Karakternya tenang", "Stabil dan daya tahannya tinggi", "Ulet dalam memulai pekerjaan", "Berusaha keras mencapai sasarannya", "Mandiri dan cermat"]'::jsonb, 'Seorang yang obyektif dan analitis.  Ia ingin terlibat dalam situasi, dan ia juga ingin memberikan bantuan dan dukungan kepada orang yang ia hormati.  Secara internal termotivasi oleh target pribadi, ia berorientasi terhadap pekerjaannya tapi juga menyukai hubungan dengan sesama.  Karena determinasinya yang kuat, ia sering berhasil dalam berbagai hal; karakternya yang tenang, stabil dan daya tahannya yang tinggi memiliki kontribusi dalam keberhasilannya.  Ulet dalam memulai pekerjaan. Ia akan berusaha keras untuk mencapai sasarannya.  Seorang yang mandiri dan cermat serta memiliki tindak lanjut yang baik.', 'Engineering and Production (Directing, Managing, Supervising), Sales, Sales Management, Service Manager, Distribution, Public Relations, Creative Designer, Office Management, Chief Engineer, Business Consultant, Chief Financial Officer, Customer Service, National Accounts Manager, Chief Accountant, Lecturer, Projects Manager, Research Planning, Human Resources, Scientific Work, Security Specialist, Solicitor, Planner, Production Administrator.'),
  (22, 'D-C-I', 'CHALLENGER', '["Seorang yang tekun", "Sensitif terhadap permasalahan", "Mempunyai keputusan yang kuat", "Kreatif  dalam memecahkan masalah", "Memiliki reaksi yang cepat", "Mampu mencari solusi permasalahan", "Banyak memberikan ide-ide.", "Usaha yang keras pada ketepatan", "Cenderung perfeksionis"]'::jsonb, 'Seorang yang sensitif terhadap permasalahan, dan memiliki kreativitas yang baik dalam memecahkan masalah. Ia dapat menyelesaikan tugas-tugas penting dalam waktu singkat karena mempunyai keputusan yang kuat. Seorang yang tekun dan memiliki reaksi yang cepat.  Ia akan meneliti dan mengejar semua kemungkinan yang ada dalam mencari solusi permasalahan.  Ia banyak memberikan ide-ide dengan berfokus pada pekerjaan. Usaha yang keras pada ketepatan akan mengimbangi keinginannya pada hasil yang terukur.  Ia cenderung perfeksionis dan dapat juga memperlambat pengambilan keputusan karena keinginannya untuk menentukan pilihan yang terbaik.', 'Technical/Scientific (Directing, Management, Supervision), Engineering, Finance, Production Planning, Personnel Disciplines, Self-Employment, Credit Manager, Planner, Lecturing, Work Study, Transport, Consultancy, Industrial Relations and Computers (Selling, Software, Systems Analyst) and General Manager.'),
  (23, 'D-C-S', 'CHALLENGER', '["Seorang yang tekun", "Sensitif terhadap permasalahan", "Mempunyai keputusan yang kuat", "Kreatif  dalam memecahkan masalah", "Memiliki reaksi yang cepat", "Mampu mencari solusi permasalahan", "Banyak memberikan ide-ide.", "Usaha yang keras pada ketepatan", "Cenderung perfeksionis"]'::jsonb, 'Seorang yang sensitif terhadap permasalahan, dan memiliki kreativitas yang baik dalam memecahkan masalah. Ia dapat menyelesaikan tugas-tugas penting dalam waktu singkat karena mempunyai keputusan yang kuat. Seorang yang tekun dan memiliki reaksi yang cepat.  Ia akan meneliti dan mengejar semua kemungkinan yang ada dalam mencari solusi permasalahan.  Ia banyak memberikan ide-ide dengan berfokus pada pekerjaan. Usaha yang keras pada ketepatan akan mengimbangi keinginannya pada hasil yang terukur.  Ia cenderung perfeksionis dan dapat juga memperlambat pengambilan keputusan karena keinginannya untuk menentukan pilihan yang terbaik.', 'Engineering, Production and Finance (Directing, Administrating, Managing and Managing Specialist Work), Scientific, Research Planning, Personnel, Trouble Shooting, Credit Control, Chief Accountant, Accountant, Chief Engineer, Work Study, Consultancy, Designer, Draughtsman, Project Work, Security Specialist, Doctor, Attorney.'),
  (24, 'I', 'COMMUNICATOR', '["Antusias", "Percaya", "Optimis", "Persuasif", "Bicara aktif", "Impulsif", "Emosional", "Ramah", "Inspirasional"]'::jsonb, 'Merupakan seorang yang antusias dan optimistik, ia lebih suka mencapai sasarannya melalui orang lain. Ia suka berhubungan dengan sesamanya - ia bahkan suka mengadakan “pesta” atau kegiatan untuk berkumpul, dan ini menunjukkan kepribadiannya yang ramah. Ia tidak suka bekerja sendirian dan cenderung bersama dengan orang lain dalam menyelesaikan proyek.  Perhatian dan fokusnya tidak sebaik apa yang dia inginkan -  maka ia membutuhkan energi yang besar untuk mampu bergerak cepat dari satu hal ke hal berikutnya tanpa penundaan.  Ia sangat menonjol dalam keterampilan berkomunikasi, dan ini merupakan salah satu kekuatan yang paling sering digunakan.  Ia memiliki kemampuan untuk memotivasi dan memberi semangat dengan kata-katanya, dan ia dikenal sebagai individu yang inspirasional. Ketika ia harus memusatkan perhatiannya pada tugas, Ia akan menjadi tidak akurat dan bahkan tidak terorganisir.  Tetapi ia akan memusatkan perhatian kepada yang harus ia senangkan, karena ia enggan sekali untuk menolak.  Ia menginginkan pengakuan sosial dan takut akan penolakan.  Ia mudah menemukan teman dan berusaha menciptakan suasana yang menyenangkan.  Ia membutuhkan seorang manajer atau supervisor untuk menentukan batas waktu yang jelas dalam pekerjaannya, ia lebih suka menggunakan gaya manajemen partisipatif yang dibangun berdasarkan hubungan yang kuat.', 'Promoting, Demonstrating, Canvassing, Marketing Services, Public Relations, Lecturing, Advertising, Publican, Publishing, Hospitality, Retail-General, Human Resources, Journalist, Singers, Technical Writing, Tour Guide, Promotional Work, Hotelier, Dancers, Host, Actors, Travel Agent, Politician, and very soft selling.'),
  (25, 'I-S', 'ADVISOR', '["Hangat", "Simpati", "Tenang dalam situasi sosial", "Pendengar yang baik", "Demonstratif", "Tidak memaksakan idenya pada orang lain", "Kurang tegas dalam memberi perintah", "Menerima kritik", "Toleran dan sabar", "Penjaga damai"]'::jsonb, 'Seorang yang mengesankan orang akan kehangatan, simpati dan pengertiannya.  Ia memiliki ketenangan dalam sebagian besar situasi sosial dan jarang tidak menyenangkan orang lain.  Faktanya, banyak orang datang padanya karena ia kelihatan sebagai pendengar yang baik.  Ia cenderung sangat demonstratif dan emosinya biasanya tampak jelas bagi orang di sekitarnya.  Ia tidak akan memaksakan idenya pada orang lain; ia tidak tegas dalam mengekspresikan atau memberi perintah.  Jika ia sangat kuat merasakan sesuatu, Ia akan bicara secara terbuka dan terus terang tentang pendiriannya.  Ia cenderung menerima kritik atas pekerjaannya sebagai serangan pribadi.  Ia dapat menjadi sangat toleran dan sabar kepada mereka yang tidak produktif di pekerjaan.  Ia merupakan "penjaga damai" dan akan bekerja untuk menjaga kedamaian dalam setiap keadaan.', 'Personnel, Welfare, Training, Hotelier, Promoting, Travel Agent, Lecturing, Upmarket/Speciality Sales, Soft/Service Selling, Beauty Therapist, Psychologist, Nursing, Human Resources, Retail-Specialist, Veterinarian, Social Work, Personal Assistant, Personnel-HR, Coach, Mentor.'),
  (26, 'I-C', 'ASSESSOR', '["Ramah", "Suka berteman", "Nyaman walapun dengan orang asing", "Mudah mengembangkan hubungan baru", "Dapat mengendalikan diri", "Sangat sosial", "Cenderung perfeksionis alamiah", "Mempromosikan tugas-tugas orang lain"]'::jsonb, 'Merupakan seorang yang ramah dan suka berteman; ia merasa nyaman walaupun dengan orang asing. Ia dapat mengembangkan hubungan baru dengan mudah, dan pada umumnya dapat mengendalikan diri sampai pada tingkat dimana ia jarang menimbulkan rasa benci pada orang lain dengan sengaja. Ia seorang yang sangat sosial, menunjukkan kepedulian dan persahabatan ketika sedang melakukan tugas-tugas di tangannya. Ia cenderung perfeksionis secara alamiah, dan akan mengisolasi dirinya jika diperlukan untuk melaksanakan pekerjaan.  Ia berkeinginan mempromosikan tugas-tugas orang lain, juga kepunyaannya.  Kadang-kadang ia salah menilai kemampuan orang lain dikarenakan pandangan-pandangannya yang optimis.', 'Teaching, Training, Inventing, Specialist Selling (Engineering, Finance or any area involving capital equipment), Project Engineer, Finance, Service Engineer or Supervising within a Technical/Specialist Area, Public Relations, Environmentalist, Marketing, Conference Organiser, Estate Agent.'),
  (27, 'I-C-D', 'ASSESSOR', '["Analitis", "Berwatak hati-hati", "Ramah pada saat merasa nyaman", "Sangat biasa dengan orang asing", "Mudah mengembangkan hubungan baru", "Dapat mengendalikan diri", "Peduli dan ramah", "Memusatkan perhatian pada penyelesaian tugas", "Perfeksionis secara alami", "Mengisolasi dirinya jika diperlukan", "Mudah diramalkan", "Berorientasi pada kualitas"]'::jsonb, 'Merupakan seseorang yang analitis, berwatak hati-hati dan ramah pada saat merasa nyaman. Ia sangat biasa dengan orang asing, karena ia dapat menilai dan menyesuaikan diri dalam hubungan mereka. Ia dapat mengembangkan hubungan baru dengan mudah ketika ia ingin melakukannya, dan pada umumnya dapat mengendalikan diri sampai pada tingkat di mana ia jarang menimbulkan rasa benci pada orang lain dengan sengaja. Ia menampilkan sikap peduli dan ramah, namun mampu memusatkan perhatian pada penyelesaian tugas yang ada. Ia cenderung perfeksionis secara alami, dan akan mengisolasi dirinya jika diperlukan untuk melaksanakan pekerjaan. Ia suka berada pada situasi yang dapat diramalkan dan tidak ada kejutan. Ia sangat berorientasi pada kualitas dan akan bekerja dengan keras untuk menyelesaikan pekerjakan dengan benar. Ia ingin orang-orang berkenan akan pekerjaan yang sudah ia selesaikan dengan baik.', 'Specialist/Technical Selling (Computer, Finance, Engineer and others, Technical/Capital Equipment Selling), Financial (Manager, Specialist), Engineering (Manager, Designer, Buyer, Draughtsman), Project Engineer, Sales Engineer, Consultant, Trainer, Lecturer, Hotelier, Travel Agent, Personnel and Marketing Services.'),
  (28, 'I-C-S', 'RESPONSIVE & THOUGHTFUL', '["High Energy", "Good Communication Skill", "To The Point", "Sensitif", "Banyak Bicara", "Need Recognation", "Need Socialism", "Anti thd Kritik", "Terlalu banyak bersosialisasi", "Leadership kurang", "Kurang Fokus", "Anti Deadline"]'::jsonb, 'Merupakan individu yang berorientasi pada orang dan lancar berkomunikasi serta loyal.  Ia cenderung sensitif dan mempunyai standard yang tinggi.  Keputusannya dibuat berdasarkan fakta dan data pendukung.  Ia sepertinya tidak bisa diam.  Ia perlu untuk lebih terus terang dan jangan terlalu subyektif.  Ia butuh pengakuan sosial dan perhatian pribadi; ia dapat cepat akrab dengan orang lain.  Ia bersahabat, antusias, informal, banyak bicara dan terlalu khawatir terhadap apa yang dipikirkan orang.  Ia menguasai banyak hal.  Ia ingin diterima sebagai anggota kelompok dan ingin mengetahui secara pasti apa yang diharapkan darinya sebelum ia memulai proyek baru.', 'Personnel, Welfare, Training, Attorney, Teaching, Accounting, Technical Instructor, Customer Services, Public Relations, Artist, Hotelier, Demonstrator, Engineering (Sales, Service, Project, Draughtsman, Designer), Specialist (Soft/Services), Selling, Purchasing, Supervising (Engineering, Production, Accounts), Administration Work, Secretarial, Industrial Relations Specialist.'),
  (29, 'S-D', 'SELF-MOTIVATED', '["Objektif & Analitis", "Mandiri", "Good planner", "Komitmen terhadap target", "Menghindari konflik", "Ingin terlibat dalam situasi", "Ingin memberikan bantuan dan dukungan", "Termotivasi oleh target pribadi", "Stabil", "Tekun"]'::jsonb, 'Merupakan seorang yang obyektif dan analitis.  Ia ingin terlibat dalam situasi, dan juga ingin memberikan bantuan dan dukungan.  Secara internal termotivasi oleh target pribadi, Ia menyukai orang-orang, tetapi juga mempunyai kemampuan untuk berorientasi pada pekerjaannya pada saat dibutuhkan.  Karena determinasinya yang kuat, ia sering berhasil dalam berbagai hal; karakternya yang tenang, stabil dan daya tahannya memiliki kontribusi akan keberhasilannya.  Keuletannya setelah memulai pekerjaan, ia akan berusaha keras untuk mendapatkan sasarannya.  Seorang yang bebas, ia orang yang cermat dan memiliki tindak lanjut yang baik.  Ia bisa menjadi tidak ramah walaupun ia pada dasarnya ia yang berorientasi pada orang; dan pada situasi yang tidak membuatnya nyaman, ia lebih suka mendukung pemimpinnya dari pada keterlibatannya dengan situasi.', 'Investigator, Researcher, Accountant, Engineering, Production/Engineering Supervisor, Computer Specialist, Architect, Transport/Warehouse Supervisor, Credit Controller, DP Supervisor, Computer Specialist, Research and Development, Private Investigator, Quality Controller, Engineering (Designer, Draughtsman, Project Engineer), Sales and Service Engineer, Property Manager, Attorney, Administration Manager'),
  (30, 'S-I', 'ADVISOR', '["Hangat", "Simpati dan Pengertian", "Tenang dalam situasi sosial", "Pendengar yang baik", "Demonstratif", "Tidak memaksakan idenya pada orang lain", "Kurang tegas dalam memberi perintah", "Menerima kritik", "Toleran dan sabar", "Penjaga damai"]'::jsonb, 'Seorang yang mengesankan orang akan kehangatan, simpati dan pengertiannya.  Ia memiliki ketenangan dalam sebagian besar situasi sosial dan jarang tidak menyenangkan orang lain.  Faktanya, banyak orang datang padanya karena ia kelihatan sebagai pendengar yang baik.  Ia cenderung sangat demonstratif dan emosinya biasanya tampak jelas bagi orang di sekitarnya.  Ia tidak akan memaksakan idenya pada orang lain; ia tidak tegas dalam mengekspresikan atau memberi perintah.  Jika ia sangat kuat merasakan sesuatu, Ia akan bicara secara terbuka dan terus terang tentang pendiriannya.  Ia cenderung menerima kritik atas pekerjaannya sebagai serangan pribadi.  Ia dapat menjadi sangat toleran dan sabar kepada mereka yang tidak produktif di pekerjaan.  Ia merupakan "penjaga damai" yang sebenarnya dan akan bekerja untuk menjaga kedamaian dalam setiap keadaan.', 'Personnel Welfare, Training, Hotelier, Promoting, Travel Agent, Lecturing, Child Care, Charitable Organizations, Soft or Service Selling, Psychologist, Therapist, Nurse, Personal Assistant, Hospitality Manager, Social Work, Student Services, Upmarket/Speciality Sales.'),
  (31, 'S-D-I', 'DIRECTOR', '["Seorang yang obyektif dan analitis", "Ingin terlibat dalam situasi", "Ingin memberikan bantuan dan dukungan", "Termotivasi oleh target pribadi", "Berorientasi terhadap pekerjaannya", "Menyukai hubungan dengan sesama", "Mempunyai determinasi yang kuat", "Karakternya tenang", "Stabil dan daya tahannya tinggi", "Ulet dalam memulai pekerjaan", "Berusaha keras mencapai sasarannya", "Mandiri dan cermat"]'::jsonb, 'Seorang yang obyektif dan analitis.  Ia ingin terlibat dalam situasi, dan ia juga ingin memberikan bantuan dan dukungan kepada orang yang ia hormati.  Secara internal termotivasi oleh target pribadi, ia berorientasi terhadap pekerjaannya tapi juga menyukai hubungan dengan sesama.  Karena determinasinya yang kuat, ia sering berhasil dalam berbagai hal; karakternya yang tenang, stabil dan daya tahannya yang tinggi memiliki kontribusi dalam keberhasilannya.  Ulet dalam memulai pekerjaan. Ia akan berusaha keras untuk mencapai sasarannya.  Seorang yang mandiri dan cermat serta memiliki tindak lanjut yang baik.', 'Engineering and Production (Supervision), Service Selling, Distribution and Warehouse Supervision/Manager, Office Management, Customer Service, System Analyst, Radio Announcer, Technical Writing, Telemarketing, TV Presenter, Project Engineer, Film Producer, Programmer, Sales/Service Engineer, Accounting, Draughtsman, Project Engineer.'),
  (32, 'S-I-D', 'ADVISOR', '["Hangat", "Simpati dan Pengertian", "Tenang dalam situasi sosial", "Pendengar yang baik", "Demonstratif", "Tidak memaksakan idenya pada orang lain", "Kurang tegas dalam memberi perintah", "Menerima kritik", "Toleran dan sabar", "Penjaga damai"]'::jsonb, 'Seorang yang mengesankan orang akan kehangatan, simpati dan pengertiannya.  Ia memiliki ketenangan dalam sebagian besar situasi sosial dan jarang tidak menyenangkan orang lain.  Faktanya, banyak orang datang padanya karena ia kelihatan sebagai pendengar yang baik.  Ia cenderung sangat demonstratif dan emosinya biasanya tampak jelas bagi orang di sekitarnya.  Ia tidak akan memaksakan idenya pada orang lain; ia tidak tegas dalam mengekspresikan atau memberi perintah.  Jika ia sangat kuat merasakan sesuatu, Ia akan bicara secara terbuka dan terus terang tentang pendiriannya.  Ia cenderung menerima kritik atas pekerjaannya sebagai serangan pribadi.  Ia dapat menjadi sangat toleran dan sabar kepada mereka yang tidak produktif di pekerjaan.  Ia merupakan "penjaga damai" yang sebenarnya dan akan bekerja untuk menjaga kedamaian dalam setiap keadaan.', 'Engineering and Production (Supervision), Service Selling, Distribution and Warehouse Supervision, Office Management, Customer Service, System Analyst, Programmer, Sales/Service Engineer, Accounting, Draughtsman, Project Engineer.'),
  (33, 'S-I-C', 'ADVOCATE', '["Stabil", "Ramah", "Detail ketika situasi membutuhkan", "Cenderung individualis", "Teguh pendirian", "Menyukai hubungan dengan orang", "Mendukung pihak yang lemah", "Ingin diterima sebagai anggota tim", "Ingin orang lain menyukainya", "Sulit membuat keputusan", "Moderat", "Cermat dan dapat diandalkan"]'::jsonb, 'Merupakan orang yang stabil, individu yang ramah yang berusaha keras membangun hubungan yang positif di tempat kerja dan di rumah.  Ia dapat menjadi sangat berorientasi detil ketika situasi membutuhkan; tetapi secara keseluruhan ia cenderung individualis, independen dan sedikit perhatian terhadap detil.  Sekali dia membuat keputusan, sangat sulit mengubah pendiriannya.  Ia menyukai hubungan dengan orang dan cenderung mendukung pihak yang lemah.  Ia akan mengambil posisi berlawanan dengan ketidaksepakatan dan merasa frustrasi jika sesuatu tidak sejalan dengannya.  Ia ingin diterima sebagai anggota tim, dan ia menginginkan orang lain menyukainya.  Ia cukup sulit membuat keputusan sampai parameter wewenang secara jelas ditentukan, dan ia mungkin cenderung tidak sungguh-sungguh jika dipaksa membuat keputusan ketika ia tidak ingin melakukannya.  Ia menginginkan orang lain yang membuat keputusan, khususnya jika ada orang yang sangat ia hargai dan hormati.  Ia cenderung moderat, cermat dan dapat diandalkan.', 'Personnel Welfare, Training, Teaching, Attorney, Accounting, Technical Instructor, Customer Service, Public Relations, Artist, Hotelier, Demonstrator, Engineer (Sales, Service, Project, Draughtsman, Designer), Specialist (Soft/Service), Selling, Purchasing, Supervising (Engineering, Production, Accounts) Administrative Work, Secretarial.'),
  (34, 'S-C-D', 'INQUIRER', '["Seorang yang baik", "Sangat berorientasi pada detil", "Sangat teliti dalam penyelesaian tugas", "Sangat berhati-hati", "Penuh pertimbangan", "Lambat adaptasi", "Kaku dan keras kepala"]'::jsonb, 'Seorang yang baik secara alamiah dan sangat berorientasi detil.  Ia peduli dengan orang-orang di sekitarnya dan mempunyai kualitas yang membuatnya sangat teliti dalam penyelesaian tugas.  Ia mempertimbangkan sekelilingnya dengan hati-hati sebelum membuat keputusan untuk melihat pengaruhnya pada mereka; saat tertentu ia terlalu hati-hati.  Jika ia merasa seseorang memanfaatkan situasi, ia akan memperlambat kerjanya sehingga dapat mengamati apa yang sedang berlangsung di sekitarnya.', 'Directing, Managing or Supervising (in Engineering, Accountancy, Research and Development and Computing disciplines), Accountant, Project Engineer, Draughtsman, Designer, Analyst, Chemist, Technician, Service Engineer, Manager, Security Specialist.'),
  (35, 'S-C-I', 'ADVOCATE', '["Stabil", "Ramah", "Detail ketika situasi membutuhkan", "Cenderung individualis", "Teguh pendirian", "Menyukai hubungan dengan orang", "Mendukung pihak yang lemah", "Ingin diterima sebagai anggota tim", "Ingin orang lain menyukainya", "Sulit membuat keputusan", "Moderat", "Cermat dan dapat diandalkan"]'::jsonb, 'Merupakan orang yang stabil, individu yang ramah yang berusaha keras membangun hubungan yang positif di tempat kerja dan di rumah.  Ia dapat menjadi sangat berorientasi detil ketika situasi membutuhkan; tetapi secara keseluruhan ia cenderung individualis, independen dan sedikit perhatian terhadap detil.  Sekali dia membuat keputusan, sangat sulit mengubah pendiriannya.  Ia menyukai hubungan dengan orang dan cenderung mendukung pihak yang lemah.  Ia akan mengambil posisi berlawanan dengan ketidaksepakatan dan merasa frustrasi jika sesuatu tidak sejalan dengannya.  Ia ingin diterima sebagai anggota tim, dan ia menginginkan orang lain menyukainya.  Ia cukup sulit membuat keputusan sampai parameter wewenang secara jelas ditentukan, dan ia mungkin cenderung tidak sungguh-sungguh jika dipaksa membuat keputusan ketika ia tidak ingin melakukannya.  Ia menginginkan orang lain yang membuat keputusan, khususnya jika ada orang yang sangat ia hargai dan hormati.  Ia cenderung moderat, cermat dan dapat diandalkan.', 'Personnel Welfare, Administrator, Advisers, Training, Teaching, Attorney, Accounting, Counseling, Technical Instructor, Customer Service, Accounting-General, Public Relations, Accounts Supervisor, Artist, Hotelier, Demonstrator, Engineer (Sales, Service, Project, Draughtsman, Designer), Specialist (Soft/Service), Selling, Purchasing, Sales Engineer, Legal, Negotiator, Student Service, Photographer, Physiotherapist, Project Engineer, Vocational Education, Supervising (Engineering, Production, Accounts) Administrative Work, Demonstrator, Secretarial, Hospitality Manager.'),
  (36, 'C-I', 'ASSESSOR', '["Analitis", "Berwatak hati-hati", "Ramah pada saat merasa nyaman", "Sangat biasa dengan orang asing", "Mudah mengembangkan hubungan baru", "Dapat mengendalikan diri", "Peduli dan ramah", "Memusatkan perhatian pada penyelesaian tugas", "Perfeksionis secara alami", "Mengisolasi dirinya jika diperlukan", "Mudah diramalkan", "Berorientasi pada kualitas"]'::jsonb, 'Merupakan seseorang yang analitis, berwatak hati-hati dan ramah pada saat merasa nyaman. Ia sangat biasa dengan orang asing, karena ia dapat menilai dan menyesuaikan diri dalam hubungan mereka. Ia dapat mengembangkan hubungan baru dengan mudah ketika ia ingin melakukannya, dan pada umumnya dapat mengendalikan diri sampai pada tingkat di mana ia jarang menimbulkan rasa benci pada orang lain dengan sengaja. Ia menampilkan sikap peduli dan ramah, namun mampu memusatkan perhatian pada penyelesaian tugas yang ada. Ia cenderung perfeksionis secara alami, dan akan mengisolasi dirinya jika diperlukan untuk melaksanakan pekerjaan. Ia suka berada pada situasi yang dapat diramalkan dan tidak ada kejutan. Ia sangat berorientasi pada kualitas dan akan bekerja dengan keras untuk menyelesaikan pekerjakan dengan benar. Ia ingin orang-orang berkenan akan pekerjaan yang sudah ia selesaikan dengan baik.', 'Sales (Technical/Specialist), Public Relations, Lecturer, Academic, Personnel Administration, Purchasing, Travel Agent, Training, Teaching, Real Estate Agent, Hospitality Administration, Sales-Technical, Hotelier, Project Engineer, Service Engineer.'),
  (37, 'C-D-I', 'CHALLENGER', '["Sangat berorientasi pada tugas", "Sensitif terhadap permasalahan", "Lebih mempedulikan tugas daripada orang", "Kukuh/keras", "Dingin", "Tidak berperasaan", "Menjaga jarak", "Membuat keputusan berdasarkan fakta", "Pendiam", "Tidak mudah percaya"]'::jsonb, 'Seorang yang sangat berorientasi pada tugas dan sensitif pada permasalahan. Ia lebih mempedulikan tugas yang ada dibanding orang-orang di sekitarnya, termasuk perasaan mereka. Ia sangat kukuh/keras dan mempunyai pendekatan yang efektif dalam pemecahan masalah. Oleh karena sifat alamiah dan keinginannya akan hasil yang terukur, ia akan tampak dingin, tidak berperasaan dan menjaga jarak. Ia membuat keputusan berdasar pada fakta, bukan emosi. ia cenderung pendiam dan tidak mudah percaya.', 'Directing, Managing or Supervising (Engineering, Research, Finance, Planning), Designer, Work Study, Sales (Technical/ Specialist), Logistic Support, Systems Analyst, Lecturer, Company Secretary, Negotiator and Purchasing.'),
  (38, 'C-D-S', 'CONTEMPLATOR', '["Berorientasi pada hal-hal detil", "Mempunyai standar tinggi untuk dirinya", "Logis dan analitis", "Ingin berbuat yang terbaik", "Selalu berpikir ada ruang untuk kemajuan", "Kompetitif", "Ingin menghasilkan mutu yang terbaik", "Mampu mencapai sasarannya", "Sangat memusatkan perhatian pada tugas", "Mantap dan dapat diandalkan"]'::jsonb, 'Berorientasi pada hal detil dan mempunyai standard tinggi untuk dirinya. Ia logis dan analitis. Ia ingin berbuat yang terbaik, dan ia selalu berpikir ada ruang untuk peningkatan/kemajuan. Ia cenderung kompetitif dan ingin menghasilkan pekerjaan dengan mutu yang terbaik. Ia sebenarnya sensitif terhadap orang-orang, tetapi karena sifat logisnya, orientasinya terhadap tugas dapat menutupinya dengan mudah. Ia suka dihargai untuk pekerjaannya yang berkualitas. Ia mampu mengerjakan tugas-tugas; dan mencapai sasarannya. Ia sangat memusatkan perhatian pada tugas yang ada, mantap dan dapat diandalkan.', 'Engineering, Research, Production and Finance (Director, Manager atau Supervisor), Work Study, Accountant, Administrator, Quality Controller, Safety Officer, Market Analyst, Planner and Personnel (Director, Manager, Administrator), MIS Manager, Security Manager, Loss Control.'),
  (39, 'C-I-D', 'ASSESSOR', '["Analitis", "Berwatak hati-hati", "Ramah pada saat merasa nyaman", "Sangat biasa dengan orang asing", "Mudah mengembangkan hubungan baru", "Dapat mengendalikan diri", "Peduli dan ramah", "Memusatkan perhatian pada penyelesaian tugas", "Perfeksionis secara alami", "Mengisolasi dirinya jika diperlukan", "Mudah diramalkan", "Berorientasi pada kualitas"]'::jsonb, 'Merupakan seseorang yang analitis, berwatak hati-hati dan ramah pada saat merasa nyaman. Ia sangat biasa dengan orang asing, karena ia dapat menilai dan menyesuaikan diri dalam hubungan mereka. Ia dapat mengembangkan hubungan baru dengan mudah ketika ia ingin melakukannya, dan pada umumnya dapat mengendalikan diri sampai pada tingkat di mana ia jarang menimbulkan rasa benci pada orang lain dengan sengaja. Ia menampilkan sikap peduli dan ramah, namun mampu memusatkan perhatian pada penyelesaian tugas yang ada. Ia cenderung perfeksionis secara alami, dan akan mengisolasi dirinya jika diperlukan untuk melaksanakan pekerjaan. Ia suka berada pada situasi yang dapat diramalkan dan tidak ada kejutan. Ia sangat berorientasi pada kualitas dan akan bekerja dengan keras untuk menyelesaikan pekerjakan dengan benar. Ia ingin orang-orang berkenan akan pekerjaan yang sudah ia selesaikan dengan baik.', 'Directing, Managing or Supervising (Engineering, Research, Finance, Planning), Designer, Work Study, Sales (Technical/Specialist), Lecturer, Company Secretary, Negotiator and Purchasing.'),
  (40, 'C-S-D', 'PRECISIONIST', '["Sistematis dan Prosedural", "Teratur & memiliki perencanaan yang baik", "Teliti", "Fokus pada detil", "Bijaksana", "Diplomatis", "Jarang menentang rekan kerjanya", "Ia sangat berhati-hati", "Mengharapkan akurasi dan standard tinggi", "Menginginkan adanya petunjuk standard", "Tidak menginginkan perubahan mendadak"]'::jsonb, 'Berpikir sistematis dan cenderung mengikuti prosedur dalam kehidupan pribadi dan pekerjaannya.  Teratur dan memiliki perencanaan yang baik, ia teliti dan fokus pada detil.  Ia bertindak dengan penuh kebijaksanaan, diplomatis dan jarang menentang rekan kerjanya dengan sengaja.  Ia sangat berhati-hati, ia sungguh-sungguh mengharapkan akurasi dan standard tinggi dalam pekerjaannya.  Ia cenderung terjebak dalam hal detil, khususnya jika harus memutuskan.  ia menginginkan adanya petunjuk standard pelaksanaan kerja dan tanpa perubahan mendadak.', 'Engineering, Research Director, Production and Finance (Director, Manager, Supervisor), Work Study, Accountant, Administrator, Quality Controller, Financial Services Manager, Safety Officer, Market Analyst, Planner and Personnel (Director, Manager, Administrator), MIS Manager, Electrician, Security Manager, Financial Researcher, Planner, Printer, Production Controller, Production Manager, Personnel Management, Loss Control.');
