-- V18: Convert SE/WA/AN to real multiple-choice structure, matching the legacy
-- source and the discovered answer key.
--
-- Re-checking resources/views/Siswa/Ujian/IST/tesIQIST.blade.php (steps 1-3) confirms
-- SE, WA, and AN are genuinely multiple choice in the legacy app: each renders
-- json_decode($item->opsi) as radio-button options with $item->jawaban as the correct
-- letter -- the exact same convention as FA/WU/ME, NOT free text. Only GE (step 4,
-- its own tiered-scoring table) and RA/ZR (steps 5-6, plain <input type="number">) are
-- genuinely free-text/numeric in the legacy app.
--
-- The previous rework (V8's original seed, never touched by V16/V17) left SE/WA/AN as
-- free-text inputs scored by exact string match against a single fabricated "correct"
-- word/phrase -- unreliable (typos, phrasing) and structurally wrong. docs/ist-result.docx
-- gives a real, verified answer key (single letter A-E) for all 20 items each of SE
-- (1-20), WA (21-40), and AN (41-60), so this migration converts them to real MC
-- structure with that real per-item answer. Real question/option text still doesn't
-- exist anywhere in this workspace (see docs/todo-ist-test.md), so question_text and
-- the option labels remain clearly-marked placeholders -- but the STRUCTURE (multiple
-- choice, 5 lettered options) and the ANSWER KEY are both now real, which is what
-- makes scoring deterministic instead of fuzzy-string-matched.
--
-- No Java or frontend changes needed: IstQuestion already supports `options`, and the
-- exam page already renders the MC branch whenever `options` is populated (already
-- exercised by ME) -- this is a pure data migration.

DELETE FROM ist_questions WHERE subtest_code IN ('SE', 'WA', 'AN');

INSERT INTO ist_questions (subtest_code, item_no, question_text, options, correct_answer) VALUES
('SE', 1, 'Soal SE nomor 1 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('SE', 2, 'Soal SE nomor 2 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('SE', 3, 'Soal SE nomor 3 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('SE', 4, 'Soal SE nomor 4 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('SE', 5, 'Soal SE nomor 5 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('SE', 6, 'Soal SE nomor 6 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('SE', 7, 'Soal SE nomor 7 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('SE', 8, 'Soal SE nomor 8 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('SE', 9, 'Soal SE nomor 9 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('SE', 10, 'Soal SE nomor 10 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('SE', 11, 'Soal SE nomor 11 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('SE', 12, 'Soal SE nomor 12 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('SE', 13, 'Soal SE nomor 13 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('SE', 14, 'Soal SE nomor 14 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('SE', 15, 'Soal SE nomor 15 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('SE', 16, 'Soal SE nomor 16 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('SE', 17, 'Soal SE nomor 17 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('SE', 18, 'Soal SE nomor 18 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('SE', 19, 'Soal SE nomor 19 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('SE', 20, 'Soal SE nomor 20 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B');

INSERT INTO ist_questions (subtest_code, item_no, question_text, options, correct_answer) VALUES
('WA', 1, 'Soal WA nomor 1 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('WA', 2, 'Soal WA nomor 2 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('WA', 3, 'Soal WA nomor 3 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('WA', 4, 'Soal WA nomor 4 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('WA', 5, 'Soal WA nomor 5 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('WA', 6, 'Soal WA nomor 6 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('WA', 7, 'Soal WA nomor 7 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('WA', 8, 'Soal WA nomor 8 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('WA', 9, 'Soal WA nomor 9 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('WA', 10, 'Soal WA nomor 10 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('WA', 11, 'Soal WA nomor 11 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('WA', 12, 'Soal WA nomor 12 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('WA', 13, 'Soal WA nomor 13 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('WA', 14, 'Soal WA nomor 14 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('WA', 15, 'Soal WA nomor 15 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('WA', 16, 'Soal WA nomor 16 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('WA', 17, 'Soal WA nomor 17 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('WA', 18, 'Soal WA nomor 18 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('WA', 19, 'Soal WA nomor 19 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('WA', 20, 'Soal WA nomor 20 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C');

INSERT INTO ist_questions (subtest_code, item_no, question_text, options, correct_answer) VALUES
('AN', 1, 'Soal AN nomor 1 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 2, 'Soal AN nomor 2 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('AN', 3, 'Soal AN nomor 3 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 4, 'Soal AN nomor 4 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 5, 'Soal AN nomor 5 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 6, 'Soal AN nomor 6 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'A'),
('AN', 7, 'Soal AN nomor 7 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 8, 'Soal AN nomor 8 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'B'),
('AN', 9, 'Soal AN nomor 9 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('AN', 10, 'Soal AN nomor 10 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 11, 'Soal AN nomor 11 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 12, 'Soal AN nomor 12 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 13, 'Soal AN nomor 13 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 14, 'Soal AN nomor 14 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 15, 'Soal AN nomor 15 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 16, 'Soal AN nomor 16 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 17, 'Soal AN nomor 17 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'C'),
('AN', 18, 'Soal AN nomor 18 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'D'),
('AN', 19, 'Soal AN nomor 19 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E'),
('AN', 20, 'Soal AN nomor 20 (menunggu teks asli dari buku soal IST)',
 '{"A": "Pilihan A", "B": "Pilihan B", "C": "Pilihan C", "D": "Pilihan D", "E": "Pilihan E"}',
 'E');
