<script lang="ts">
  import { enhance } from '$app/forms';
  import { PUBLIC_API_URL } from '$env/static/public';
  let { data, form } = $props();
  let role = $state('siswa'); let schools = $state<any[]>([]); let searching = $state(false); let saved = $state(false);
  const base = (PUBLIC_API_URL || '/api/v1').replace(/\/$/, '');
  async function searchSchools(event: Event) { const q=(event.currentTarget as HTMLInputElement).value.trim(); if(q.length<2){schools=[];return;} searching=true; try { const r=await fetch(`${base}/public/schools?search=${encodeURIComponent(q)}`); schools=(await r.json()).items ?? []; } finally { searching=false; } }
</script>
<svelte:head><title>Mulai di Assessment</title></svelte:head>
<main class="onboard"><a href="/">← Beranda</a><h1>Lengkapi aksesmu di Assessment</h1><p>Akunmu sudah siap untuk tes gratis. Agar dapat mengikuti asesmen sekolah atau bekerja sebagai staf, kirim pengajuan di bawah. Superadmin akan meninjau dan mengaktifkan aksesmu.</p>
{#if form?.error}<p class="error">{form.error}</p>{/if}{#if form?.success || saved}<p class="ok">Pengajuan terkirim. Periksa status di bawah; setelah disetujui, masuk kembali untuk memakai role baru.</p>{/if}
<form method="POST" action="?/request" use:enhance={() => { saved=false; return async ({update})=>{await update();saved=true;}; }}><label>Nama lengkap<input name="requesterName" required /></label><label>Email aktif<input name="requesterEmail" type="email" required /></label><label>Ajukan sebagai<select name="requestedRole" bind:value={role}><option value="siswa">Siswa</option><option value="gurubk">Guru BK</option><option value="psikolog">Psikolog</option></select></label>{#if role !== 'psikolog'}<label>Cari dan pilih sekolah<input placeholder="Ketik minimal 2 huruf" oninput={searchSchools} />{#if searching}<small>Mencari…</small>{/if}<select name="schoolId" required><option value="">Pilih sekolah</option>{#each schools as school}<option value={school.id}>{school.name}{school.city ? ` — ${school.city}` : ''}</option>{/each}</select></label>{/if}<label>Keterangan (opsional)<textarea name="note" rows="3"></textarea></label><button>Kirim pengajuan</button></form>
<section><h2>Status pengajuan</h2>{#if data.requests.length===0}<p>Belum ada pengajuan.</p>{:else}{#each data.requests as item}<article><strong>{item.requestedRole}</strong>{#if item.schoolName} · {item.schoolName}{/if}<span class={`status ${item.status}`}>{item.status}</span>{#if item.reviewNote}<p>{item.reviewNote}</p>{/if}</article>{/each}{/if}</section></main>
<style>.onboard{max-width:44rem;margin:0 auto;padding:3rem 1.25rem;display:grid;gap:1rem}.onboard h1{font-family:var(--lp-font-display);font-size:clamp(2rem,5vw,3rem);margin:0}.onboard p{color:var(--lp-ink-2)}form,section{border:1px solid var(--lp-rule);border-radius:1rem;padding:1.25rem;display:grid;gap:.9rem;background:#fff}label{display:grid;gap:.35rem;font-weight:600}input,select,textarea{font:inherit;padding:.65rem;border:1px solid var(--lp-rule);border-radius:.55rem}button{justify-self:start;border:0;border-radius:.55rem;background:var(--lp-accent-deep);color:#fff;padding:.7rem 1rem;font:inherit}.error{color:#b42318}.ok{color:#166534}.status{float:right;border-radius:99px;padding:.12rem .5rem;font-size:.8rem;background:#e5e7eb}.status.approved{background:#dcfce7}.status.rejected{background:#fee2e2}</style>
