<script lang="ts">import { enhance } from '$app/forms';let {data,form}=$props();</script>
<svelte:head><title>Persetujuan Pengajuan</title></svelte:head>
<div class="wrap">
  <h2>Persetujuan Pengajuan</h2>
  <p>Tinjau identitas, role, dan sekolah sebelum akses atau sekolah baru diaktifkan. Pengguna yang disetujui perlu masuk kembali agar sesi memuat role baru.</p>
  {#if form?.error}<p class="error">{form.error}</p>{/if}
  <section><h3>Pengajuan akses</h3>
  {#if data.requests.length===0}<p>Tidak ada pengajuan akses pending.</p>{:else}{#each data.requests as r}<article><h4>{r.requesterName} <small>{r.requesterEmail}</small></h4><p><strong>{r.requestedRole}</strong>{#if r.schoolName} · {r.schoolName}{/if}</p>{#if r.note}<p>{r.note}</p>{/if}<form method="POST" action="?/approve" use:enhance><input type="hidden" name="id" value={r.id}/><input name="note" placeholder="Catatan persetujuan (opsional)"/><button>Setujui akses</button></form><form method="POST" action="?/reject" use:enhance><input type="hidden" name="id" value={r.id}/><input name="note" placeholder="Alasan penolakan"/><button class="reject">Tolak</button></form></article>{/each}{/if}</section>
  <section><h3>Pendaftaran sekolah</h3>
  {#if data.schoolRequests.length===0}<p>Tidak ada pendaftaran sekolah pending.</p>{:else}{#each data.schoolRequests as r}<article><h4>{r.schoolName}</h4><p><strong>Kontak:</strong> {r.contactName} · {r.contactEmail}</p><p>{[r.npsn && `NPSN ${r.npsn}`, r.address, r.city, r.province, r.phone].filter(Boolean).join(' · ')}</p>{#if r.note}<p>{r.note}</p>{/if}<form method="POST" action="?/approveSchool" use:enhance><input type="hidden" name="id" value={r.id}/><input name="note" placeholder="Catatan persetujuan (opsional)"/><button>Setujui &amp; buat sekolah</button></form><form method="POST" action="?/rejectSchool" use:enhance><input type="hidden" name="id" value={r.id}/><input name="note" placeholder="Alasan penolakan"/><button class="reject">Tolak</button></form></article>{/each}{/if}</section>
</div>
<style>.wrap{display:grid;gap:1rem}.wrap>p,section>p{color:var(--lp-ink-2)}section{display:grid;gap:.75rem}section h3{margin:.5rem 0 0}article{border:1px solid var(--lp-rule);border-radius:.8rem;padding:1rem;background:#fff}h4{margin:0}small{font-weight:400;color:var(--lp-ink-2)}article p{margin:.45rem 0}form{display:flex;gap:.5rem;margin-top:.55rem}input{flex:1;padding:.5rem;border:1px solid var(--lp-rule);border-radius:.45rem}button{border:0;background:var(--lp-accent-deep);color:white;border-radius:.45rem;padding:.5rem .75rem}.reject{background:#9f1239}.error{color:#b42318}</style>
